// Answer-to-hint dictionary for FR
// Hints follow these rules:
// - Verbs: dictionary form (infinitive)
// - Articles: "article"
// - Pronouns: "pronom"
// - Other words: word type in French

export const answerHints: Record<string, string> = {
  "aboieront": "aboyer",
  "'irons jamais": "aller",
  "a": "avoir",
  "A-t-il": "avoir",
  "A-t-il compris": "comprendre",
  "As-tu": "avoir",
  "As-tu compris": "comprendre",
  "a fait": "faire",
  "a été": "être",
  "a grandi": "grandir",
  "a habité": "habiter",
  "à laquelle": "pronom relatif",
  "à leurs parents": "préposition",
  "a lu": "lire",
  "lis": "lire",
  "me détends": "se détendre",
  "a quittée": "quitter",
  "prépares": "préparer",
  "à ma meilleure amie": "préposition",
  "a marché": "marcher",
  "a mis": "mettre",
  "à mon ami": "préposition",
  "a monté": "monter",
  "a passé": "passer",
  "a préféré": "préférer",
  "à nos élèves": "préposition",
  "a reçu": "recevoir",
  "a sonné": "sonner",
  "a su": "savoir",
  "à ta grand-mère": "préposition",
  "a terminé": "terminer",
  "a rédigé": "rédiger",
  "a couru": "courir",
  "a peint": "peindre",
  "a fini": "finir",
  "a rempli": "remplir",
  "a raté": "rater",
  "a obtenu": "obtenir",
  "construisait": "construire",
  "pratiquait": "pratiquer",
  "se rendait": "se rendre",
  "organiserons": "organiser",
  "ont organisé": "organiser",
  "s'est ouverte": "s'ouvrir",
  "skiait": "skier",
  "cuisait": "cuire",
  "cultiverait": "cultiver",
  "cultiverions": "cultiver",
  "cessera": "cesser",
  "racontait": "raconter",
  "réserveront": "réserver",
  "s'est levé": "se lever",
  "achetée": "acheter",
  "achètes": "acheter",
  "acquerras": "acquérir",
  "agissez": "agir",
  "Agiter": "agiter",
  "ai": "avoir",
  "a perdu": "perdre",
  "a oublié": "oublier",
  "avons terminé": "terminer",
  "avons rédigé": "rédiger",
  "avons refait": "refaire",
  "avons visité": "visiter",
  "visiterez": "visiter",
  "rentrerons": "rentrer",
  "rentrerez": "rentrer",
  "est allé": "aller",
  "a disparu": "disparaître",
  "a pris": "prendre",
  "ont brisé": "briser",
  "ont préparé": "préparer",
  "préparerez": "préparer",
  "ont marché": "marcher",
  "est tombée": "tomber",
  "est tombé": "tomber",
  "est devenu": "devenir",
  "est devenue": "devenir",
  "brûlait": "brûler",
  "murmurait": "murmurer",
  "a apporté": "apporter",
  "nageait": "nager",
  "déjeunions": "déjeuner",
  "écrivait": "écrire",
  "écrives": "écrire",
  "écrive": "écrire",
  "écriras": "écrire",
  "écrirais": "écrire",
  "écrirait": "écrire",
  "buvait": "boire",
  "ai bu": "boire",
  "a mangé": "manger",
  "a compris": "comprendre",
  "a entendu": "entendre",
  "ont entendu": "entendre",
  "ont observé": "observer",
  "a éteint": "éteindre",
  "suis sorti": "sortir",
  "sommes arrivés": "arriver",
  "sommes installés": "installer",
  "est revenu": "revenir",
  "avons brisé": "briser",
  "avons perdu": "perdre",
  "a rangé": "ranger",
  "a signé": "signer",
  "avons traversé": "traverser",
  "ont commencé": "commencer",
  "a chanté": "chanter",
  "as peint": "peindre",
  "avons réparé": "réparer",
  "a allumé": "allumer",
  "ont changé": "changer",
  "a composé": "composer",
  "a trouvé": "trouver",
  "avez trouvé": "trouver",
  "ont chanté": "chanter",
  "as posé": "poser",
  "a fermé": "fermer",
  "avons raté": "rater",
  "a ouvert": "ouvrir",
  "a attrapé": "attraper",
  "a renversé": "renverser",
  "ont manqué": "manquer",
  "avons tourné": "tourner",
  "avons fermé": "fermer",
  "a laissé": "laisser",
  "avez oublié": "oublier",
  "avons regardé": "regarder",
  "ai fermé": "fermer",
  "aideras": "aider",
  "aie": "avoir",
  "Aie": "avoir",
  "aie fait": "faire",
  "aie prises": "prendre",
  "aie rencontrée": "rencontrer",
  "aient comprise": "comprendre",
  "aient fini": "finir",
  "aient réussi": "réussir",
  "aient résolu": "résoudre",
  "aies résolu": "résoudre",
  "aies saisi": "saisir",
  "ait résolu": "résoudre",
  "aient signé": "signer",
  "aient découvert": "découvrir",
  "ait découvert": "découvrir",
  "ait trahi": "trahir",
  "aient rendu": "rendre",
  "aient eu": "avoir",
  "aies acceptée": "accepter",
  "aies accepté": "accepter",
  "ayez manqué": "manquer",
  "aies compris": "comprendre",
  "aies comprise": "comprendre",
  "aies été": "être",
  "aies fini": "finir",
  "aies oublié": "oublier",
  "aies obtenu": "obtenir",
  "aies participé": "participer",
  "aies obtenue": "obtenir",
  "aies perdue": "perdre",
  "aies quitté": "quitter",
  "aies regardé": "regarder",
  "aies relevé": "relever",
  "aies suivi": "suivre",
  "aies tenu": "tenir",
  "aies tenue": "tenir",
  "aies vu": "voir",
  "aille": "aller",
  "ailles": "aller",
  "aimerais": "aimer",
  "aimerait": "aimer",
  "aimerait voyager": "aimer",
  "ait": "avoir",
  "ait abandonné": "abandonner",
  "ait accepté": "accepter",
  "ait compris": "comprendre",
  "ait demandé": "demander",
  "ait démontré": "démontrer",
  "ait dépassé": "dépasser",
  "ait éliminé": "éliminer",
  "ait fait": "faire",
  "ait atteint": "atteindre",
  "ait fini": "finir",
  "ait lu": "lire",
  "ait obtenu": "obtenir",
  "ait pris": "prendre",
  "ait proposée": "proposer",
  "ait proposé": "proposer",
  "ait remédié": "remédier",
  "ait reçu": "recevoir",
  "ait remporté": "remporter",
  "ait rencontrée": "rencontrer",
  "ait raté": "rater",
  "ait réussi": "réussir",
  "ait servi": "servir",
  "ait terminé": "terminer",
  "ayez formulé": "formuler",
  "ait gagné": "gagner",
  "ait travaillé": "travailler",
  "ait vu": "voir",
  "allaient": "aller",
  "allais": "aller",
  "allait": "aller",
  "allez": "aller",
  "Allez-y": "aller",
  "allions": "aller",
  "allons": "aller",
  "Allons": "aller",
  "appelle": "appeler",
  "appellent": "appeler",
  "appelles": "appeler",
  "appellerai": "appeler",
  "appellerait": "appeler",
  "appréciions": "apprécier",
  "apprenais": "apprendre",
  "apprends": "apprendre",
  "apprend": "apprendre",
  "apprendrait": "apprendre",
  "appuieras": "appuyer",
  "architectes": "nom",
  "mécanicien": "nom",
  "coiffeuse": "nom",
  "avocate": "nom",
  "pilote": "nom",
  "dentistes": "nom",
  "éclate": "éclater",
  "ravage": "ravager",
  "crie": "crier",
  "gravit": "gravir",
  "franchit": "franchir (le présent de narration raconte un événement passé au présent)",
  "reteniez": "retenir",
  "retentit": "retentir",
  "apparaît": "apparaître",
  "s'écrasent": "s'écraser",
  "fuit": "fuir",
  "saisit": "saisir",
  "frappe": "frapper",
  "se lève": "se lever",
  "se lèvera": "se lever",
  "raconte": "raconter",
  "libère": "libérer",
  "monte": "monter (le présent de narration raconte un événement passé au présent)",
  "attaque": "attaquer",
  "emprunte": "emprunter",
  "brise": "briser (le présent de narration raconte un événement passé au présent)",
  "emporte": "emporter",
  "glisse": "glisser",
  "examine": "examiner",
  "arrive": "arriver",
  "arrivions": "arriver",
  "arrivent": "arriver",
  "arrivera": "arriver",
  "arriveras": "arriver",
  "arriverez": "arriver",
  "arriverons": "arriver",
  "aurons atteint": "atteindre",
  "arriveront": "arriver",
  "aurons fini": "finir",
  "vont arriver": "arriver",
  "va arriver": "arriver",
  "atteindras": "atteindre",
  "arrivés": "arriver",
  "as": "avoir",
  "as-tu": "avoir",
  "Asseyez-vous": "s'asseoir",
  "assez de": "article",
  "suffisamment de": "quantité",
  "assistions": "assister",
  "assumes": "assumer",
  "Attachez": "attacher",
  "atteigniez": "atteindre",
  "atteint": "atteindre",
  "attend": "attendre",
  "attendait": "attendre",
  "attendons": "attendre",
  "attends": "attendre",
  "a attendu": "attendre",
  "attendu": "attendre",
  "attendras": "attendre",
  "au": "article",
  "augmenteront": "augmenter",
  "auquel": "pronom relatif",
  "aura composé": "composer",
  "aura envoyé": "envoyer",
  "aura eu": "avoir",
  "aura perdu": "perdre",
  "aura trouvé": "trouver",
  "aura été": "être",
  "aurai fini": "finir",
  "aurai préparé": "préparer",
  "aurai terminé": "terminer",
  "auraient": "avoir",
  "auraient découvert": "découvrir",
  "auraient dû": "devoir",
  "auraient pu": "pouvoir",
  "auraient voulu": "vouloir",
  "auraient fait": "faire",
  "auraient vu": "voir",
  "aurais": "avoir",
  "aurais dû": "devoir",
  "aurais pu": "pouvoir",
  "aurais eu": "avoir",
  "aurais oublié": "oublier",
  "aurais réussi": "réussir",
  "aurais voulu": "vouloir",
  "aurait agi": "agir",
  "aurait aimé": "aimer",
  "aurait dû": "devoir",
  "aurait pu": "pouvoir",
  "aurait eu": "avoir",
  "aurait fait": "faire",
  "aurait occupé": "occuper",
  "aurait quitté": "quitter",
  "aurait vaincu": "vaincre",
  "vainc": "vaincre",
  "aurait été rédigé": "rédiger",
  "aurait remarqué": "remarquer",
  "ait remarqué": "remarquer",
  "a remarqué": "remarquer",
  "remarque": "remarquer",
  "remarquera": "remarquer",
  "remarquait": "remarquer",
  "aurait été": "être",
  "aurait": "avoir",
  "auras fini": "finir",
  "auras l'occasion": "avoir",
  "auras terminé": "terminer",
  "auras": "avoir",
  "aurez examiné": "examiner",
  "aurez fini": "finir",
  "aurez préparé": "préparer",
  "aurez rassemblé": "rassembler",
  "sembleraient": "sembler",
  "auriez dû": "devoir",
  "auriez peur": "avoir",
  "auriez pu": "pouvoir",
  "auriez": "avoir",
  "aurions": "avoir",
  "aurions acheté": "acheter",
  "aurions dû": "devoir",
  "aurions pu": "pouvoir",
  "aurons achevé": "achever",
  "aurons": "avoir",
  "auront oublié": "oublier",
  "auront réparé": "réparer",
  "aux": "article",
  "auxquelles": "pronom relatif",
  "auxquels": "pronom relatif",
  "avaient couru": "courir",
  "avaient cru": "croire",
  "avaient pris": "prendre",
  "avaient décidé": "décider",
  "avaient déjà étudié": "étudier",
  "avaient toujours cru": "croire",
  "avaient fini": "finir",
  "avaient fermé": "fermer",
  "avaient observé": "observer",
  "avaient le droit": "avoir",
  "avaient lu": "lire",
  "avaient oublié": "oublier",
  "avaient étudié": "étudier",
  "avaient été": "être",
  "aient été": "être",
  "ait validé": "valider",
  "avait fini": "finir",
  "avaient mangé": "manger",
  "avaient visité": "visiter",
  "avaient": "avoir",
  "avais dit": "dire",
  "avais pris": "prendre",
  "avais vu": "voir",
  "avais reçue": "recevoir",
  "aviez reçu": "recevoir",
  "avais": "avoir",
  "avait appelé": "appeler",
  "avait appris": "apprendre",
  "avait arrêté": "arrêter",
  "avait besoin de ce dont elle": "avoir besoin",
  "avait bu": "boire",
  "avait commencé": "commencer",
  "avait compris": "comprendre",
  "avait descendu": "descendre",
  "avait démarré": "démarrer",
  "démarré": "démarrer",
  "désirerait": "désirer",
  "avait dit": "dire",
  "avait déjà fermé": "fermer",
  "avait entendu": "entendre",
  "avait eu": "avoir",
  "avait fait": "faire",
  "avait fermé": "fermer",
  "avait gonflé": "gonfler",
  "avait perdu": "perdre",
  "avait pris": "prendre",
  "avait laissé": "laisser",
  "avait laissés": "laisser",
  "avait lu": "lire",
  "avait lus": "lire",
  "avait menti": "mentir",
  "avait quitté": "quitter",
  "avait reçues": "recevoir",
  "avait raté": "rater",
  "avait terminé": "terminer",
  "avait volé": "voler",
  "avait vu": "voir",
  "avait écrites": "écrire",
  "avait écrit": "écrire",
  "avait été accroché": "accrocher",
  "avait-on fermé": "fermer",
  "avait été": "être",
  "avait été signé": "être",
  "avait accroché": "accrocher",
  "avait examiné": "examiner",
  "avait": "avoir",
  "avait-il compris": "comprendre",
  "avez expliqué": "expliquer",
  "avez fini": "finir",
  "avez rencontré": "rencontrer",
  "avez terminé": "terminer",
  "avez": "avoir",
  "aviez": "avoir",
  "avez-vous": "avoir",
  "N'avez-vous pas": "avoir",
  "N'avez-vous pas terminé": "avoir",
  "aviez demandé": "demander",
  "aviez expliqué": "expliquer",
  "aviez relu": "relire",
  "avions eu": "avoir",
  "avions défini": "définir",
  "avions étudié": "étudier",
  "avions organisé": "organiser",
  "avions retourné": "retourner",
  "avions signé": "signer",
  "avions préparé": "préparer",
  "avions vendu": "vendre",
  "avions-nous vu": "voir",
  "avions fermé": "fermer",
  "avions": "avoir",
  "avoir regardé": "regarder",
  "avoir lu": "lire",
  "avoir vendu": "vendre",
  "avons corrigé": "corriger",
  "avons classé": "classer",
  "avons eu": "avoir",
  "avons eu faim": "avoir",
  "avons pris": "prendre",
  "avons travaillé": "travailler",
  "avons vu": "voir",
  "avons": "avoir",
  "ayez acceptée": "accepter",
  "ayez accepté": "accepter",
  "ayez": "avoir",
  "ayez apprise": "apprendre",
  "ayez appris": "apprendre",
  "ayez faite": "faire",
  "ayez fini": "finir",
  "ayez inventé": "inventer",
  "ayez perdu": "perdre",
  "ayez lu": "lire",
  "ait prévenu": "prévenir",
  "ayez parlé": "parler",
  "ayez pu assister": "pouvoir",
  "ayez pu": "pouvoir",
  "ayez refusée": "refuser",
  "ayez reçue": "recevoir",
  "ayez reçu": "recevoir",
  "ayez terminés": "terminer",
  "ayez terminé": "terminer",
  "ayez trouvé": "trouver",
  "ayons compris": "comprendre",
  "ayons fait": "faire",
  "ayons manqué": "manquer",
  "ayons trouvée": "trouver",
  "ayons trouvé": "trouver",
  "ayons": "avoir",
  "ayant": "avoir",
  "beaucoup de": "quantité",
  "Beaucoup de": "article",
  "Peu de": "quantité",
  "Trop de": "quantité",
  "Nous nous étions dépêchés": "se dépêcher",
  "beaucoup": "adverbe",
  "a beaucoup": "adverbe",
  "a bien": "adverbe",
  "a bien réussi": "réussir",
  "a déjà lu": "lire",
  "as mal rédigé": "rédiger",
  "avons beaucoup travaillé": "travailler",
  "ont beaucoup voyagé": "voyager",
  "avez mal": "adverbe",
  "avons déjà": "adverbe",
  "ont toujours": "adverbe",
  "bois": "boire",
  "boit": "boire",
  "boive": "boire",
  "bu": "boire",
  "bougions": "bouger",
  "bout": "bouillir",
  "brillait": "briller",
  "buvais": "boire",
  "buvions": "boire",
  "buvons": "boire",
  "bâtissent": "bâtir",
  "ce dont": "pronom relatif",
  "ce à quoi": "pronom relatif",
  "Ce dont": "pronom relatif",
  "Ce que": "pronom relatif",
  "Ce qui": "pronom relatif",
  "changerais": "changer",
  "changeront": "changer",
  "chantait": "chanter",
  "chanté": "chanter",
  "cherchais": "chercher",
  "cherché": "chercher",
  "choisi": "choisir",
  "choisiras": "choisir",
  "choisirez": "choisir",
  "Choisis": "choisir",
  "commandait": "commander",
  "commence": "commencer",
  "commencera": "commencer",
  "commencerait": "commencer",
  "commençaient": "commencer",
  "commençons": "commencer",
  "comprenais": "comprendre",
  "comprenait": "comprendre",
  "comprendrez": "comprendre",
  "comprendrai": "comprendre",
  "comprends": "comprendre",
  "comprenne": "comprendre",
  "comprennent": "comprendre",
  "comprend": "comprendre",
  "comprendra": "comprendre",
  "comprendrait": "comprendre",
  "comprenions": "comprendre",
  "craignions": "craindre",
  "craignons": "craindre",
  "craignaient": "craindre",
  "craindraient": "craindre",
  "craindrons": "craindre",
  "craindre": "craindre",
  "craindrions": "craindre",
  "confiiez": "confier",
  "connaissez": "se connaître",
  "connais": "connaître",
  "connaît": "connaître",
  "connaisse": "connaître",
  "connaissais": "connaître",
  "connaissait": "connaître",
  "connaissiez": "connaître",
  "connaîtrais": "connaître",
  "connaîtrait": "connaître",
  "connaîtriez": "connaître",
  "a connu": "connaître",
  "ai connu": "connaître",
  "connus": "connaître",
  "Conserver": "conserver",
  "continuons": "continuer",
  "Continue": "continuer",
  "Observez": "observer",
  "construirais": "construire",
  "corrigées": "corriger",
  "courent": "courir",
  "courrai": "courir",
  "courrons": "courir",
  "criiez": "crier",
  "copiions": "copier",
  "croies": "croire",
  "croyiez": "croire",
  "croiriez": "croire",
  "croyez": "croire",
  "cru": "croire",
  "couvert": "couvrir",
  "cuisinerais": "cuisiner",
  "d'": "article",
  "d'oeufs et de": "article",
  "danse": "danser",
  "dansions": "danser",
  "de": "article",
  "de l'": "article",
  "de laquelle": "pronom relatif",
  "de partir": "partir",
  "descend": "descendre",
  "descende": "descendre",
  "descendait": "descendre",
  "défendront": "défendre",
  "demande": "demander",
  "demande pas": "demander",
  "demandais": "demander",
  "demanderais": "demander",
  "des": "article",
  "desquelles": "pronom relatif",
  "desquels": "pronom relatif",
  "dessines": "dessiner",
  "devaient": "devoir",
  "devenue": "devenir",
  "devez": "devoir",
  "deviendrons": "devenir",
  "devons": "devoir",
  "devrais faire": "devoir",
  "devrais": "devoir",
  "devrait": "devoir",
  "devrez": "devoir",
  "devriez": "devoir",
  "devrions": "devoir",
  "dire": "dire",
  "dirais": "dire",
  "dirait": "dire",
  "direz": "dire",
  "diriez": "dire",
  "dis": "dire",
  "disait": "dire",
  "dise": "dire",
  "dises": "dire",
  "disiez": "dire",
  "dit": "dire",
  "dites": "dire",
  "dites-la-nous": "dire",
  "doives": "devoir",
  "doive": "devoir",
  "dû": "devoir",
  "donne": "donner",
  "a donné": "donner",
  "donnait": "donner",
  "donnera": "donner",
  "donnerait": "donner",
  "donne-le-moi": "donner",
  "donne-m'en": "donner",
  "donne-moi": "donner",
  "donnent rendez-vous": "se donner rendez-vous",
  "donnerai": "donner",
  "donnons": "donner",
  "Dors": "dormir",
  "dorment": "dormir",
  "dont": "pronom relatif",
  "dormais": "dormir",
  "dormait": "dormir",
  "dormions": "dormir",
  "du": "article",
  "duquel": "pronom relatif",
  "déjà": "adverbe",
  "déjeunait": "déjeuner",
  "désirais": "désirer",
  "détruit": "détruire",
  "développeur": "nom",
  "dîner": "dîner",
  "Dépêchons-nous": "se dépêcher",
  "Détends-toi": "se détendre",
  "effaçait": "effacer",
  "emploieront": "employer",
  "en": "pronom",
  "Entendez": "entendre",
  "entendent": "entendre",
  "entends": "entendre",
  "entre": "entrer",
  "enverront": "envoyer",
  "envoie": "envoyer",
  "envoie-les-toi": "envoyer",
  "envoient": "envoyer",
  "envoies": "envoyer",
  "envoyer": "envoyer",
  "envoyées": "envoyer",
  "envoyez": "envoyer",
  "envoyons": "envoyer",
  "es allé / es allée": "aller",
  "es arrivé / es arrivée": "arriver",
  "es": "être",
  "essaies": "essayer",
  "essayé": "essayer",
  "essaierez": "essayer",
  "essuierons": "essuyer",
  "essuiera": "essuyer",
  "Est-ce qu'ils sont": "être",
  "Est-ce qu'il est": "aller",
  "Est-ce qu'il est allé": "aller",
  "Est-ce qu'il est allé à l'école ?": "aller",
  "Est-ce que": "comprendre",
  "est": "être",
  "est descendue": "descendre",
  "est entré": "entrer",
  "est entrée": "entrer",
  "est parti": "partir",
  "est retourné": "retourner",
  "est sortie": "sortir",
  "Est-ce": "être",
  "eu": "avoir",
  "eûmes": "avoir",
  "examinerez": "examiner",
  "examiné": "examiner",
  "Excusez-moi": "s'excuser",
  "eût terminé": "terminer",
  "Fais attention": "faire",
  "fais": "faire",
  "faisais": "faire",
  "faisait": "faire",
  "faisaient": "faire",
  "faisiez": "faire",
  "faisions": "faire",
  "faisons pas": "faire",
  "Ne faisons pas": "faire",
  "fait": "faire",
  "faites": "faire",
  "fasse": "faire",
  "fasses": "faire",
  "fassent": "faire",
  "fassiez": "faire",
  "fassions": "faire",
  "faisons": "faire",
  "faut": "falloir",
  "faudrait": "falloir",
  "fera": "faire",
  "feront": "faire",
  "font": "faire",
  "ferais": "faire",
  "feraient": "faire",
  "ferait": "faire",
  "feriez": "faire",
  "ferions": "faire",
  "Fermez": "fermer",
  "fini": "finir",
  "finisse": "finir",
  "finit": "finir",
  "finir": "infinitif",
  "finirai": "finir",
  "finirait": "finir",
  "finiras": "finir",
  "finira": "finir",
  "finirais": "finir",
  "finis": "finir",
  "avait arrosé": "arroser",
  "finissent": "finir",
  "finissiez": "finir",
  "finissais": "finir",
  "finisses": "finir",
  "finiriez": "finir",
  "finissez": "finir",
  "finissons": "finir",
  "finirez": "finir",
  "finirions": "finir",
  "finirons": "finir",
  "finissions": "finir",
  "Fournissez": "fournir",
  "fourniront": "fournir",
  "fondu": "fondre",
  "allemand": "nom",
  "l'allemand": "nom",
  "français": "nom",
  "grandis": "grandir",
  "grandisse": "grandir",
  "choisisses": "choisir",
  "choisisse": "choisir",
  "choisit": "choisir",
  "choisis": "choisir",
  "choisir": "choisir",
  "choisirais": "choisir",
  "parlions": "parler",
  "réussissiez": "réussir",
  "réfléchissions": "réfléchir",
  "gèle": "geler",
  "habitait": "habiter",
  "habite": "habiter",
  "habitiez": "habiter",
  "habitions": "habiter",
  "honnêtement": "adverbe",
  "Il faut": "falloir",
  "Invite": "inviter",
  "inviterons": "inviter",
  "invité": "inviter",
  "ira": "aller",
  "irait": "aller",
  "iriez": "aller",
  "irions": "aller",
  "irons": "aller",
  "japonais": "nom",
  "jette": "jeter",
  "jettent": "jeter",
  "jettes": "jeter",
  "jetterez": "jeter",
  "joint": "joindre",
  "lisaient": "lire",
  "emmenait": "emmener",
  "mangiez": "manger",
  "nettoyais": "nettoyer",
  "mangeait": "manger",
  "commençais": "commencer",
  "rangeait": "ranger",
  "commencions": "commencer",
  "commençait": "commencer",
  "annonçaient": "annoncer",
  "annonçait": "annoncer",
  "lancions": "lancer",
  "rangeiez": "ranger",
  "partageait": "partager",
  "partagions": "partager",
  "commenciez": "commencer",
  "annonçent": "annoncer",
  "joue": "jouer",
  "jouait": "jouer",
  "jouions": "jouer",
  "l'": "...",
  "L'": "...",
  "l'appelle": "appeler",
  "la France": "nom",
  "la leçon": "nom",
  "la lui": "pronom",
  "la": "...",
  "La": "...",
  "la-lui": "pronom",
  "la-moi": "pronom",
  "laquelle": "pronom relatif",
  "le lui": "pronom",
  "le mandarin": "nom",
  "le signer": "signer",
  "le sache": "savoir",
  "le sait": "savoir",
  "le saura": "savoir",
  "le savait": "savoir",
  "le suédois": "nom",
  "le": "...",
  "Le": "...",
  "les": "...",
  "Les": "...",
  "les accompagner": "...",
  "les écoutez": "...",
  "les leur": "pronom",
  "les y": "pronom",
  "le-lui": "pronom",
  "le-moi": "pronom",
  "les-leur": "pronom",
  "lesquelles": "pronom relatif",
  "lesquels": "pronom relatif",
  "leur en": "pronom",
  "leur": "pronom",
  "de leur": "pronom",
  "je vais": "aller",
  "Lisez": "lire",
  "lirais": "lire",
  "lira": "lire",
  "lirait": "lire",
  "lit": "lire",
  "Lisant": "lire",
  "Lisons": "lire",
  "Lu": "lire",
  "Lire": "lire",
  "Lise": "lire",
  "lisait": "lire",
  "lisais": "lire",
  "lire": "lire",
  "lise": "lire",
  "lisent": "lire",
  "livrerons": "livrer",
  "lu": "lire",
  "lues": "lire",
  "lui en dis": "dire",
  "lui": "pronom",
  "Lève-toi": "se lever",
  "m'": "pronom",
  "m'appellerais": "appeler",
  "Mange": "manger",
  "mange": "manger",
  "mangeons": "manger",
  "mangeras": "manger",
  "Manges": "manger",
  "manges": "manger",
  "mangions": "manger",
  "manque": "manquer",
  "manquent": "manquer",
  "marchait": "marcher",
  "marché": "marcher",
  "parlé": "parler",
  "a parlé": "parler",
  "dormi": "dormir",
  "ont dormi": "dormir",
  "pleuré": "pleurer",
  "a pleuré": "pleurer",
  "couru": "courir",
  "a dormi": "dormir",
  "mangé": "manger",
  "travaillé": "travailler",
  "ont couru": "courir",
  "me contacteriez": "contacter",
  "me la dis": "dire",
  "me la donne": "donner",
  "me la": "pronom",
  "me lavais": "se laver",
  "me le prête": "prêter",
  "me le": "pronom",
  "me les envoyez": "envoyer",
  "me lève": "se lever",
  "me reposer": "se reposer",
  "me": "pronom",
  "met": "mettre",
  "mettes": "mettre",
  "mettras": "mettre",
  "mettrais": "mettre",
  "mettre": "mettre",
  "mis": "mettre",
  "montre-les-lui": "montrer",
  "montrerai": "montrer",
  "morte": "mourir",
  "mourra": "mourir",
  "mourrez": "mourir",
  "mécaniciens": "nom",
  "neige": "neiger",
  "né": "naître",
  "n'ai": "avoir",
  "n'as pas": "négation",
  "n'avons pas": "négation",
  "n'ait abandonné": "abandonner",
  "n'ait pas abandonné": "abandonner",
  "n'aura pas fini": "finir",
  "n'aurais": "avoir",
  "n'aurait": "avoir",
  "n'aurait invité personne": "inviter",
  "n'aurait jamais vu": "voir",
  "n'aurez jamais eu": "avoir",
  "n'avaient rien dit": "dire",
  "n'avaient pas encore pris": "prendre",
  "avaient pas encore pris": "prendre",
  "n'avais invité personne": "inviter",
  "n'avait pas mangé": "manger",
  "n'avions jamais vu": "voir",
  "n'en": "article",
  "n'est": "être",
  "n'est pas": "négation",
  "ne sont pas": "négation",
  "n'ont": "avoir",
  "n'ont pas": "négation",
  "n'a pas": "négation",
  "n'avez pas": "négation",
  "n'avait pas lu": "lire",
  "n'avait jamais reçu": "recevoir",
  "n'avait pas encore examiné": "examiner",
  "n'y va pas": "aller",
  "n'y": "pronom",
  "Nage": "nager",
  "nageons": "nager",
  "nagerai": "nager",
  "ne change": "changer",
  "ne comprendrais pas": "comprendre",
  "ne dirais rien": "dire",
  "ne lui fassiez des reproches": "faire",
  "ne mange pas de bonbons": "manger",
  "ne nous battons pas": "se battre",
  "ne parle pas": "parler",
  "ne parlez pas fort": "parler",
  "ne pas exposer": "exposer",
  "ne pas laisser": "laisser",
  "ne stationnez pas": "stationner",
  "ne rencontreriez": "rencontrer",
  "ne réveille": "réveiller",
  "ne s'est": "se lever",
  "ne se fâche": "se fâcher",
  "ne se serait pas trompée": "se tromper",
  "ne serais": "être",
  "ne soit trop tard": "être",
  "ne soit": "être",
  "ne soyez trop fatigués": "être",
  "ne dise": "dire",
  "ne fassiez": "faire",
  "ne mettions": "mettre",
  "ne s'en aille": "s'en aller",
  "ne voies": "voir",
  "nettoierai": "nettoyer",
  "nettoie": "nettoyer",
  "nettoient": "nettoyer",
  "nettoiera": "nettoyer",
  "nettoies": "nettoyer",
  "nettoyé": "nettoyer",
  "nourrissent": "nourrir",
  "nous dépêchions": "se dépêcher",
  "nous couchions": "se coucher",
  "nous inquiétons": "s'inquiéter",
  "s'inquiète": "s'inquiéter",
  "nous les montrez": "montrer",
  "nous les": "pronom",
  "nous nous étions dépêchés": "se dépêcher",
  "nous nous étions rendu compte": "se rendre compte",
  "nous reposerions": "se reposer",
  "se brossait": "se brosser",
  "se rasait": "se raser",
  "nous retrouverons": "se retrouver",
  "nous souvenons": "se souvenir",
  "nous voyions": "voir",
  "étions déjà partis": "partir",
  "nous": "pronom",
  "nés": "naître",
  "obligiez": "obliger",
  "offert": "offrir",
  "ont attendu": "attendre",
  "ont vendu": "vendre",
  "ont visité": "visiter",
  "court": "courir",
  "découvre": "découvrir",
  "découvre pas": "découvrir",
  "découvrira": "découvrir",
  "découvrait": "découvrir",
  "repère": "repérer",
  "ont éteint": "éteindre",
  "ont pu": "pouvoir",
  "ont": "avoir",
  "oubliions": "oublier",
  "oublié": "oublier",
  "ouvert": "ouvrir",
  "où": "pronom relatif",
  "paie": "payer",
  "paierai": "payer",
  "paierons": "payer",
  "parcoure": "parcourir",
  "parlait": "parler",
  "parle": "parler",
  "parle-lui": "parler",
  "parlons": "se parler",
  "partons": "partir",
  "part": "partir",
  "partent": "partir",
  "parte": "partir",
  "partes": "partir",
  "partie": "partir",
  "préparé": "préparer",
  "partions": "partir",
  "partir": "infinitif",
  "partiras": "partir",
  "pars": "partir",
  "passais": "passer",
  "passait": "passer",
  "passent": "passer",
  "passer": "passer",
  "passerez": "passer",
  "passions": "passer",
  "payons": "payer",
  "payé": "payer",
  "peint": "peindre",
  "pensait": "penser",
  "penses": "penser",
  "perd": "perdre",
  "perde": "perdre",
  "perdais": "perdre",
  "perds": "perdre",
  "perdez": "perdre",
  "perdu": "perdre",
  "Permettez-moi": "permettre",
  "personne": "pronom indéfini",
  "peu de": "article",
  "peuvent": "pouvoir",
  "peut": "pouvoir",
  "peux": "pouvoir",
  "plaît": "plaire",
  "plais": "plaire",
  "plaisait": "plaire",
  "plairait": "plaire",
  "plaisent": "plaire",
  "plaçais": "placer",
  "plaçons": "placer",
  "pleut": "pleuvoir",
  "pleuvra": "pleuvoir",
  "pleuvrait": "pleuvoir",
  "Pourriez": "pouvoir",
  "pourra": "pouvoir",
  "pourrai": "pouvoir",
  "pourraient": "pouvoir",
  "pourrez": "pouvoir",
  "pourrais": "pouvoir",
  "pourras": "pouvoir",
  "pourrait": "pouvoir",
  "pourriez": "pouvoir",
  "pourrions accepter": "pouvoir",
  "pourrions": "pouvoir",
  "pourront": "pouvoir",
  "poursuive": "poursuivre",
  "poursuives": "poursuivre",
  "poursuivra": "poursuivre",
  "poursuivait": "poursuivre",
  "pouvais": "pouvoir",
  "pouvait": "pouvoir",
  "pouvions": "pouvoir",
  "pouvons": "pouvoir",
  "pouviez": "pouvoir",
  "Prendriez": "prendre",
  "prenait": "prendre",
  "prend": "prendre",
  "prendrais": "prendre",
  "prendrait": "prendre",
  "prendraient": "prendre",
  "prendrions": "prendre",
  "prendrons": "prendre",
  "Prends": "prendre",
  "prends": "prendre",
  "prenne": "prendre",
  "prennes": "prendre",
  "preniez": "prendre",
  "prenions": "prendre",
  "prenons": "prendre",
  "presse": "presser",
  "pris": "prendre",
  "prise": "prendre",
  "prises": "prendre",
  "Prépare-toi": "se préparer",
  "profitiez": "profiter",
  "promets-toi": "promettre",
  "préparions": "préparer",
  "présent": "temps verbal",
  "prête-la-nous": "prêter",
  "puisse": "pouvoir",
  "puissent": "pouvoir",
  "puisses": "pouvoir",
  "puissiez": "pouvoir",
  "puissions": "pouvoir",
  "qu'elles aient complété": "compléter",
  "aient complété": "compléter",
  "aient terminé": "terminer",
  "qu'il ait échoué": "échouer",
  "ait échoué": "échouer",
  "que": "pronom relatif",
  "que tu sois": "être",
  "qu'elle soit": "être",
  "qu'ils fassent": "faire",
  "qu'elle poursuive": "poursuivre",
  "qu'il dise": "dire",
  "que vous soyez": "être",
  "qui jouent dans le parc": "jouer",
  "qui": "pronom relatif",
  "quitte": "quitter",
  "rangé": "ranger",
  "rangeras": "ranger",
  "rapidamente": "adverbe",
  "rappelle": "rappeler",
  "rappellent": "rappeler",
  "rappelles": "rappeler",
  "rappelons": "rappeler",
  "recevait": "recevoir",
  "recommandés": "recommander",
  "rembourserai": "rembourser",
  "reconnaissions": "reconnaître",
  "Regarde": "regarder",
  "redoublez": "redoubler",
  "regardaient": "regarder",
  "regarde": "regarder",
  "regardent": "regarder",
  "regardons": "regarder",
  "regardé": "regarder",
  "rejette": "rejeter",
  "rejettent": "rejeter",
  "rejettes": "rejeter",
  "rejetterons": "rejeter",
  "rejoint": "rejoindre",
  "Remplissons": "remplir",
  "rempli": "remplir",
  "rencontre": "rencontrer",
  "rencontrez": "rencontrer",
  "rencontrerez": "rencontrer",
  "rencontreriez": "rencontrer",
  "rencontriez": "rencontrer",
  "rencontrâtes": "rencontrer",
  "rencontrerons": "rencontrer",
  "rendait visite à": "rendre visite à",
  "rendu": "rendre",
  "Rentre": "rentrer",
  "rentre": "rentrer",
  "rentrent": "rentrer",
  "renouvelleront": "renouveler",
  "reprennent": "reprendre",
  "retrouvais": "retrouver",
  "retrouvent": "se retrouver",
  "se connait": "se connaître",
  "se connaissent": "se connaître (action mutuelle)",
  "se disent": "se dire (action mutuelle)",
  "se saluent": "se saluer (action mutuelle)",
  "se retrouvent": "se retrouver (action mutuelle)",
  "se téléphonent": "se téléphoner (action mutuelle)",
  "reviennes": "revenir",
  "reçois": "recevoir",
  "reçoit": "recevoir",
  "réalise": "réaliser",
  "réfléchissaient": "réfléchir",
  "répondez": "répondre",
  "réponds": "répondre",
  "Réponds": "répondre",
  "répondes": "répondre",
  "répondre": "répondre",
  "répondras": "répondre",
  "répondrais": "répondre",
  "répondrai": "répondre",
  "résolu": "résoudre",
  "résoudra": "résoudre",
  "résoudrait": "résoudre",
  "résout": "résoudre",
  "résolve": "résoudre",
  "résolvions": "résoudre",
  "résolvons": "résoudre",
  "résoudrons": "résoudre",
  "résoudre": "résoudre",
  "résoudrions": "résoudre",
  "résolvaient": "résoudre",
  "résoudraient": "résoudre",
  "réussi": "réussir",
  "réussira": "réussir",
  "réussirais": "réussir",
  "réussisse": "réussir",
  "réussissait": "réussir",
  "réussit": "réussir",
  "réveille": "réveiller",
  "réveille pas": "réveiller",
  "réveillera": "réveiller",
  "réveillait": "réveiller",
  "Réveillons-nous": "se réveiller",
  "s'agit": "s'agir",
  "s'agit de": "s'agir",
  "s'en aperçoive": "s'apercevoir",
  "s'en aperçoit": "s'apercevoir",
  "s'en aperçoivent": "s'apercevoir",
  "s'en aperçoivent pas": "s'apercevoir",
  "s'en aperçoivent déjà": "s'apercevoir",
  "s'en est aperçu": "s'apercevoir",
  "s'en apercevait": "s'apercevoir",
  "s'en apercevoir": "s'apercevoir",
  "s'en sont aperçus": "s'apercevoir",
  "s'est assis": "s'asseoir",
  "s'est cassé": "se casser",
  "s'est réveillée": "se réveiller",
  "se sont blessés": "se blesser",
  "s'est peigné": "se peigner",
  "se sont retrouvés": "se retrouver",
  "s'est dépêchée": "se dépêcher",
  "s'est lavée": "se laver",
  "s'est éteinte": "s'éteindre",
  "s'habillait": "s'habiller",
  "s'étaient habillées": "s'habiller",
  "s'étaient regardés": "se regarder",
  "s'étaient rencontrés": "se rencontrer",
  "s'était levé": "se lever",
  "s'était levée": "se lever",
  "s'était passé": "se passer",
  "s'était souvenue": "se souvenir",
  "s'était tordu": "se tordre",
  "s'était ouverte": "s'ouvrir",
  "s'était": "se souvenir",
  "Sache": "savoir",
  "sache": "savoir",
  "sait": "savoir",
  "veuille": "vouloir",
  "veut": "vouloir",
  "voulait": "vouloir",
  "veuillent": "vouloir",
  "saches": "savoir",
  "sachiez": "savoir",
  "sachions": "savoir",
  "saura": "savoir",
  "savait": "savoir",
  "Saisissons": "saisir",
  "saisie": "saisir",
  "saisirez": "saisir",
  "saisira": "saisir",
  "saisir": "saisir",
  "saisisse": "saisir",
  "saisissait": "saisir",
  "saisis": "saisir",
  "sauras": "savoir",
  "saurait": "savoir",
  "saurez": "savoir",
  "sauriez": "savoir",
  "saurions": "savoir",
  "saurons": "savoir",
  "savez": "savoir",
  "savais": "savoir",
  "saviez": "savoir",
  "se sent": "se sentir",
  "se sera perdu": "se perdre",
  "se sera réveillée": "se réveiller",
  "se soient battus": "se battre",
  "se soient reposées": "se reposer",
  "se soit levé": "se lever",
  "se soit mise": "se mettre",
  "se soit trompée": "se tromper",
  "se sont amusées": "s'amuser",
  "se sont dépêchés": "se dépêcher",
  "se souvenaient": "se souvenir",
  "regretteras": "regretter",
  "se terminent": "se terminer",
  "sentait": "sentir",
  "sera arrivé": "arriver",
  "sera arrivée": "arriver",
  "sera montée": "monter",
  "sera": "être",
  "serai": "être",
  "seraient venus": "venir",
  "seraient": "être",
  "serais allé": "aller",
  "serais parti": "partir",
  "serais": "être",
  "serait annulé": "être",
  "serait": "être",
  "seras": "être",
  "serez": "être",
  "seriez": "être",
  "serions": "être",
  "serions allés": "aller",
  "seront parties": "partir",
  "seront": "être",
  "Sois": "être",
  "sois partie": "partir",
  "sois": "être",
  "soit allé": "aller",
  "soit arrivée": "arriver",
  "soit partie": "partir",
  "soit revenue": "revenir",
  "soit venue": "venir",
  "soit": "être",
  "sommes allés": "aller",
  "sommes allés / sommes allées": "aller",
  "sommes restés": "rester",
  "resterions": "rester",
  "sommes": "être",
  "serons": "être",
  "Sont-ils": "être",
  "sont": "être",
  "sont-ils": "être",
  "sont-ils rentrés": "être",
  "Sont-ils rentrés": "rentrer",
  "sont arrivés": "arriver",
  "sont descendues": "descendre",
  "sont descendus": "descendre",
  "sont devenus": "devenir",
  "sont passées": "passer",
  "Sortez": "sortir",
  "sort": "sortir",
  "sorte": "sortir",
  "sortait": "sortir",
  "sortirait": "sortir",
  "sortons": "sortir",
  "sorties": "sortir",
  "soufflait": "souffler",
  "souffert": "souffrir",
  "souhaitais": "souhaiter",
  "souhaiterions": "souhaiter",
  "souhaiteriez": "souhaiter",
  "soumises": "soumettre",
  "soyez partis": "partir",
  "soyez venu(s)": "venir",
  "soyez venus": "venir",
  "Soyons": "être",
  "soyez": "être",
  "soyons arrivés": "arriver",
  "soyons d'accord": "être",
  "soyons partis": "partir",
  "soyons": "être",
  "Suivez": "suivre",
  "suive": "suivre",
  "suivre": "suivre",
  "suit": "suivre",
  "suivra": "suivre",
  "suffit": "suffire",
  "suis sorti / suis sortie": "sortir",
  "suis": "être",
  "suiviez": "suivre",
  "suivions": "suivre",
  "suivons": "suivre",
  "suivrons": "suivre",
  "suivrions": "suivre",
  "suivraient": "suivre",
  "suivaient": "suivre",
  "sur lequel": "pronom relatif",
  "surmonterons": "surmonter",
  "symphonie": "nom",
  "t'": "pronom",
  "t'assois": "s'asseoir",
  "t'étais blessé": "se blesser",
  "avait choisi": "choisir",
  "avait cueillies": "cueillir",
  "avions attendu": "attendre",
  "te couche": "se coucher",
  "te couches": "se coucher",
  "te dépêche": "se dépêcher",
  "te la": "pronom",
  "te": "pronom",
  "tenais": "tenir",
  "teniez": "tenir",
  "terminer": "terminer",
  "terminerai": "terminer",
  "terminerez": "terminer",
  "termines": "terminer",
  "terminés": "terminer",
  "tiendra": "tenir",
  "tiendras": "tenir",
  "tiens": "tenir",
  "tiennes": "tenir",
  "tenir": "tenir",
  "touche": "toucher",
  "toujours": "adverbe",
  "traiterons": "traiter",
  "travaillait": "travailler",
  "travaille": "travailler",
  "travaillerai": "travailler",
  "travaillez": "travailler",
  "trop de": "article",
  "trompez": "se tromper",
  "trompiez": "se tromper",
  "tromperez": "se tromper",
  "trouve": "trouver",
  "trouve pas": "trouver",
  "trouvais": "trouver",
  "trouverais": "trouver",
  "trouveras": "trouver",
  "trouviez": "trouver",
  "téléphone-nous": "téléphoner",
  "téléphones": "téléphoner",
  "Un": "article",
  "un": "article",
  "un film": "nom",
  "une avocate": "nom",
  "une infirmière": "nom",
  "une": "article",
  "utiliserez": "utiliser",
  "Va": "aller",
  "va": "aller",
  "va marcher": "marcher",
  "va partir": "partir",
  "va pleuvoir": "pleuvoir",
  "va tomber": "tomber",
  "Vas": "aller",
  "Vas-y": "aller",
  "vais": "aller",
  "vas": "aller",
  "va prendre": "prendre",
  "vaut": "valoir",
  "Veuillez": "vouloir",
  "venais": "venir",
  "vendons": "vendre",
  "vendrons": "vendre",
  "venez": "venir",
  "veniez": "venir",
  "venions": "venir",
  "verrai": "voir",
  "verrais": "voir",
  "verrait": "voir",
  "voit": "voir",
  "voyait": "voir",
  "voyais": "voir",
  "irons jamais": "aller",
  "verrai personne": "voir",
  "verras": "voir",
  "atteindrez": "atteindre",
  "verrez": "voir",
  "verriez": "voir",
  "voyez": "voir",
  "voyiez": "voir",
  "verrons": "rencontrer",
  "veux": "vouloir",
  "viendrai": "venir",
  "viendrait": "venir",
  "viendraient": "venir",
  "viendras": "venir",
  "vienne": "venir",
  "viennes": "venir",
  "vient": "venir",
  "viens": "venir",
  "venir": "venir",
  "visiterais": "visiter",
  "visité": "visiter",
  "vivait": "vivre",
  "vivra": "vivre",
  "vivrait": "vivre",
  "vive": "vivre",
  "vivions": "vivre",
  "vit": "vivre",
  "vivons": "vivre",
  "vivrons": "vivre",
  "vivre": "vivre",
  "vivrions": "vivre",
  "vivraient": "vivre",
  "vivaient": "vivre",
  "voie": "voir",
  "vois": "voir",
  "vont": "aller",
  "voudra": "vouloir",
  "voudrais": "vouloir",
  "voudrait": "vouloir",
  "voulais": "vouloir",
  "vouliez": "vouloir",
  "voulu": "vouloir",
  "vous couchiez": "se coucher",
  "vous les": "pronom",
  "vous levez": "se lever",
  "vous plaignez": "se plaindre",
  "se plaignent": "se plaindre",
  "se plaignent pas": "se plaindre",
  "se plaindront": "se plaindre",
  "se plaignaient": "se plaindre",
  "se sont plaints": "se plaindre",
  "vous préparez": "se préparer",
  "vous soyez souvenus": "se souvenir",
  "vous êtes habillés/habillées": "s'habiller",
  "voyageons": "voyager",
  "voyagerais": "voyager",
  "vu": "voir",
  "vérifi era": "vérifier",
  "vérifierais": "vérifier",
  "vérifiions": "vérifier",
  "vérifiiez": "vérifier",
  "y a": "y avoir",
  "y en": "pronom",
  "y va": "aller",
  "y": "pronom",
  "Écoute": "écouter",
  "écoutais": "écouter",
  "écouterais": "écouter",
  "Écoutons": "écouter",
  "écoutiez": "écouter",
  "écris": "écrire",
  "écrit": "écrire",
  "écris-leur": "écrire",
  "écrivent": "s'écrire",
  "épelle": "épeler",
  "épellent": "épeler",
  "épelles": "épeler",
  "épellera": "épeler",
  "établi": "établir",
  "établirons": "établir",
  "étaient rentrées": "rentrer",
  "étaient parties": "partir",
  "étaient partis": "partir",
  "étaient": "être",
  "étaient-ils rentrés": "rentrer",
  "étais venu": "venir",
  "avais-je compris": "comprendre",
  "avais appelé": "appeler",
  "étais": "être",
  "était-elle arrivée": "arriver",
  "était-elle sortie": "sortir",
  "était allée": "aller",
  "était arrivé": "arriver",
  "était arrivée": "arriver",
  "étaient arrivés": "arriver",
  "était devenu": "devenir",
  "était entré": "entrer",
  "était retournée": "retourner",
  "était parti": "partir",
  "était partie": "partir",
  "était sortie": "sortir",
  "était venue": "venir",
  "était venu": "venir",
  "était": "être",
  "être": "être",
  "étiez": "être",
  "étions arrivés": "arriver",
  "étions": "être",
  "étudie": "étudier",
  "étudierait": "étudier",
  "étudiez": "étudier",
  "étudions": "étudier",
  "étudiions": "étudier",
  "êtes trompés": "se tromper",
  "êtes venu": "venir",
  "êtes": "être",
  "être allés": "aller",
  "soient allés": "aller",
  "être parti": "partir",
  "mal": "adverbe",
  "Avez-vous": "avoir",
  "Avez-vous terminé": "terminer",
  "ne partirai pas": "partir",
  "Auriez-vous": "avoir",
  "soient": "être",
  "soient partis": "partir",
  "Continuons": "continuer",
  "Ayons": "avoir",
  "Ayez": "avoir",
  "N'y va pas": "aller",
  "Prends-en": "prendre",
  "N'en prends pas": "prendre",
  "Ne les écoutez pas": "écouter",
  "N'attendons pas": "attendre",
  "Regarde-la": "regarder",
  "Prends-les": "prendre",
  "Mange-les": "manger",
  "Écoute-le": "écouter",
  "Lisez-la": "lire",
  "Parle-lui": "parler",
  "Écris-leur": "écrire",
  "Donne-moi": "donner",
  "Téléphone-nous": "téléphoner",
  "Répondez-lui": "répondre",
  "Ne la regarde pas": "regarder",
  "Ne lui parlez pas": "parler",
  "Ne te lève pas": "se lever",
  "Ne te dépêche pas": "se dépêcher",
  "Ne vous levez pas": "se lever",
  "Ne nous dépêchons pas": "se dépêcher",
  "Ne nous reposons pas": "se reposer",
  "Ne touche pas": "toucher",
  "Bois": "boire",
  "Repose-toi": "se reposer",
  "Fais": "faire",
  "Reposez-vous": "se reposer",
  "Excusez": "excuser",
  "Ne parlez pas": "parler",
  "Ne mange pas": "manger",
  "Apporte-la-moi": "apporter",
  "Donne-m'en": "donner",
  "Ne les mangez pas": "manger",
  "Ne l'appelle pas": "appeler",
  "Donne-le-moi": "donner",
  "Montre-les-lui": "montrer",
  "Prête-la-nous": "prêter",
  "Envoie-les-lui": "envoyer",
  "Dites-la-nous": "dire",
  "Ne me la donne pas": "donner",
  "Ne nous les montrez pas": "montrer",
  "Ne me le prête pas": "prêter",
  "Ne la lui dis pas": "dire",
  "Ne me les donnez pas": "donner",
  "Ne parle pas": "parler",
  "N'y": "pronom",
  "N'en": "article",
  "Ne parlez pas fort": "parler",
  "Ne mange pas de bonbons": "manger",
  "Ne nous battons pas": "se battre",
  "Ne stationnez pas": "stationner",
  "Ne cours pas": "courir",
  "Laver": "laver",
  "Ne pas exposer": "exposer",
  "Ne pas laisser": "laisser",
  "polonais": "nom",
  "souvenons": "se souvenir",
  "pratique": "pratiquer",
  "préparez": "se préparer",
  "Le mandarin": "nom",
  "avait mangé": "manger",
  "avaient dépensé": "dépenser",
  "t'étais arrêté": "s'arrêter",
  "avait détruit": "détruire",
  "avait étudié": "étudier",
  "avait révisé": "réviser",
  "avions oublié": "oublier",
  "avais prêté": "prêter",
  "avait envoyé": "envoyer",
  "avait changé": "changer",
  "avait oublié": "oublier",
  "est venu": "venir",
  "est allée": "aller",
  "serait parti": "partir",
  "serait venu": "venir",
  "serait allée": "aller",
  "serait arrivée": "arriver",
  "seraient partis": "partir",
  "aurait compris": "comprendre",
  "aurait mangé": "manger",
  "aurait perdu": "perdre",
  "aurait commencé": "commencer",
  "aurait détruit": "détruire",
  "aurait étudié": "étudier",
  "aurait raté": "rater",
  "aurait fini": "finir",
  "aurait fallu": "falloir",
  "aurait envoyé": "envoyer",
  "aurait changé": "changer",
  "aurait oublié": "oublier",
  "auraient dépensé": "dépenser",
  "aurait réussi": "réussir",
  "auraient réussi": "réussir",
  "aurions oublié": "oublier",
  "aurais prêté": "prêter",
  "avait changer": "changer",
  "avait commencer": "commencer",
  "avait commencée": "commencer",
  "était commencé": "commencer",
  "avait eu oublié": "oublier",
  "avait oubliée": "oublier",
  "était perdu": "perdre",
  "avaient parti": "partir",
  "seront partis": "partir",
  "aura commencé": "commencer",
  "aura changé": "changer",
  "aura oublié": "oublier",
  "partait": "partir",
  "partirait": "partir",
  "partaient": "partir",
  "perdait": "perdre",
  "venait": "venir",
  "dépensaient": "dépenser",
  "t'arrêtais": "s'arrêter",
  "détruisait": "détruire",
  "étudiait": "étudier",
  "ratait": "rater",
  "rataient": "rater",
  "ratent": "rater",
  "ratent pas": "rater",
  "rateront": "rater",
  "finissait": "finir",
  "quittait": "quitter",
  "prêtais": "prêter",
  "changeait": "changer",
  "oubliait": "oublier",
  "ont dépensé": "dépenser",
  "a commencé": "commencer",
  "t'es arrêté": "s'arrêter",
  "a détruit": "détruire",
  "a étudié": "étudier",
  "sont partis": "partir",
  "avons oublié": "oublier",
  "a quitté": "quitter",
  "as prêté": "prêter",
  "a changé": "changer",
  "terminait": "terminer",
  "aurait terminé": "terminer",
  "avait oublier": "oublier",
  "te serais arrêté": "s'arrêter",
  "Il a réussi son examen parce qu'il avait beaucoup révisé.": "réviser",
  "Il a réussi son examen parce qu'il a beaucoup révisé.": "réviser",
  "Il a réussi son examen parce qu'il révisait beaucoup.": "réviser",
  "Il a réussi son examen parce qu'il aurait beaucoup révisé.": "réviser",
  "Quand j'ai ouvert la lettre, j'ai compris qu'il avait déjà envoyé sa réponse.": "envoyer",
  "Quand j'ai ouvert la lettre, j'ai compris qu'il a déjà envoyé sa réponse.": "envoyer",
  "Quand j'ai ouvert la lettre, j'ai compris qu'il envoyait déjà sa réponse.": "envoyer",
  "Quand j'ai ouvert la lettre, j'ai compris qu'il aurait déjà envoyé sa réponse.": "envoyer",
  "vivront": "vivre",
  "vont vivre": "vivre",
  "démissionnerai": "démissionner",
  "portera": "porter",
  "va porter": "porter",
  "décollera": "décoller",
  "calera": "caler",
  "paiera": "payer",
  "va payer": "payer",
  "entrera": "entrer",
  "va entrer": "entrer",
  "atteindra": "atteindre",
  "adopterait": "adopter",
  "va atteindre": "atteindre",
  "brûlera": "brûler",
  "va mordre": "mordre",
  "mordra": "mordre",
  "vont augmenter": "augmenter",
  "vais quitter": "quitter",
  "quitterai": "quitter",
  "va frapper": "frapper",
  "frappera": "frapper",
  "débordera": "déborder",
  "raterons": "rater",
  "enverras": "envoyer",
  "obtiendra": "obtenir",
  "obtient": "obtenir",
  "obtiennes": "obtenir",
  "obtienne": "obtenir",
  "s'effondrera": "s'effondrer",
  "va s'effondrer": "s'effondrer",
  "atterrira": "atterrir",
  "entendrait": "entendre",
  "réussisses": "réussir",
  "aidiez": "aider",
  "terminerait": "terminer",
  "décidera": "décider",
  "fermerait": "fermer",
  "lises": "lire",
  "partirais": "partir",
  "pleuve": "pleuvoir",
  "aies": "avoir",
  "viendrais": "venir",
  // Section 21 (hypothèses) input answers
  "aimez": "aimer",
  "obtiendras": "obtenir",
  "iront": "aller",
  "il pleut": "pleuvoir",
  "réservons": "réserver",
  "gagnera": "gagner",
  "reposez-vous": "se reposer",
  "coupons": "couper",
  "Ferme": "fermer",
  "déclenchez": "déclencher",
  "achèterions": "acheter",
  "prenais": "prendre",
  "comprendriez": "comprendre",
  // Added for sections 11/13–20 (elision restructure + new content)
  "à": "préposition",
  "à eux": "préposition",
  "à l'": "préposition",
  "à la": "préposition",
  "À laquelle": "pronom interrogatif",
  "à lui": "préposition",
  "a peu": "avoir",
  "a vu": "voir",
  "a-t-elle": "avoir",
  "A-t-elle": "avoir",
  "a-t-il": "avoir",
  "absolument": "adverbe",
  "acheter": "acheter",
  "actifs": "adjectif",
  "actives": "adjectif",
  "actuelle": "adjectif",
  "agréable": "adjectif",
  "ailleurs": "adverbe",
  "ainsi": "adverbe",
  "amère": "adjectif",
  "amoureuse": "adjectif",
  "ancienne": "adjectif",
  "anciennes": "adjectif",
  "Apparemment": "adverbe",
  "apporte-t-il": "apporter",
  "attentive": "adjectif",
  "au printemps": "préposition",
  "au-dessus de": "préposition",
  "aucun": "pronom indéfini",
  "aucune": "pronom indéfini",
  "aujourd'hui": "adverbe",
  "aussi": "adverbe",
  "aussi belles": "comparatif",
  "aussi fière": "comparatif",
  "aussi grands": "comparatif",
  "aussi polie": "comparatif",
  "aussi simple": "comparatif",
  "autant": "comparatif",
  "autant d'": "comparatif",
  "autant de": "comparatif",
  "autant que": "comparatif",
  "Autrichien": "nom",
  "aux nôtres": "pronom",
  "Auxquels": "pronom interrogatif",
  "avec": "préposition",
  "avons peut-être": "avoir",
  "avons souvent": "avoir",
  "bateaux": "adjectif",
  "beaux": "adjectif",
  "bel": "adjectif",
  "belle": "adjectif",
  "bien": "adverbe",
  "bien écouter": "écouter",
  "blanche": "adjectif",
  "bleus": "adjectif",
  "bon": "adjectif",
  "bouge": "bouger",
  "bretonne": "adjectif",
  "brève": "adjectif",
  "brillamment": "adverbe",
  "c'est": "être",
  "C'est": "être",
  "c’est": "être",
  "C'étaient": "être",
  "c'était": "être",
  "Ça": "pronom",
  "Ça y est": "expression",
  "ce": "pronom",
  "Ce": "déterminant",
  "ce qu'": "pronom relatif",
  "ce que": "pronom relatif",
  "ce qui": "pronom relatif",
  "ce sont": "être",
  "Ce sont": "être",
  "Ce vieux": "adjectif",
  "cela": "pronom",
  "Cela": "pronom",
  "cela dit": "expression",
  "celle": "pronom",
  "celle qui": "pronom",
  "celle-ci": "pronom",
  "Celle-là": "pronom",
  "celles": "pronom",
  "celles où": "pronom",
  "Celles-ci": "pronom",
  "celui": "pronom",
  "Celui": "pronom",
  "celui qui": "pronom",
  "celui-ci": "pronom",
  "Certaines": "pronom indéfini",
  "Certains": "pronom indéfini",
  "ces journaux-ci": "nom",
  "Cet": "déterminant",
  "Cette montagne-là": "nom",
  "ceux": "pronom",
  "ceux dont": "pronom",
  "ceux-là": "pronom",
  "Ceux-là": "pronom",
  "chacune": "pronom indéfini",
  "Chacune": "pronom indéfini",
  "Chaque": "déterminant",
  "cher": "adjectif",
  "chère": "adjectif",
  "chères": "adjectif",
  "chez": "préposition",
  "Chez": "préposition",
  "chez le coiffeur": "préposition",
  "chez moi": "préposition",
  "chez nous": "préposition",
  "claire": "adjectif",
  "combien": "adverbe interrogatif",
  "Combien de": "adverbe interrogatif",
  "comment": "adverbe interrogatif",
  "Comment": "adverbe interrogatif",
  "constamment": "adverbe",
  "contents": "adjectif",
  "Coréennes": "adjectif",
  "couramment": "adverbe",
  "courtes": "adjectif",
  "coûte": "coûter",
  "cries-tu": "pronom interrogatif",
  "cuisine": "cuisiner",
  "curieuse": "adjectif",
  "d'autre": "pronom indéfini",
  "d'autres": "pronom indéfini",
  "d'eux": "pronom",
  "d'extraordinaire": "adjectif",
  "d'important": "adjectif",
  "D'où": "pronom interrogatif",
  "d'urgent": "adjectif",
  "dangereuses": "adjectif",
  "dans": "préposition",
  "dans l'": "préposition",
  "dans la": "préposition",
  "dans le": "préposition",
  "dans une": "préposition",
  "de bizarre": "adjectif",
  "de bon": "adjectif",
  "de facile": "adjectif",
  "de gentil": "adjectif",
  "de la": "préposition",
  "De laquelle": "pronom interrogatif",
  "de mal en pis": "expression",
  "de meilleurs": "adjectif",
  "l'habitude": "expression",
  "la frousse": "expression",
  "le droit": "expression",
  "l'occasion": "expression",
  "avons l'habitude": "expression",
  "fais la tête": "expression",
  "a la frousse": "expression",
  "faire attention": "expression",
  "nous avons faim": "expression",
  "ont peur": "expression",
  "as peur": "expression",
  "avons peur": "expression",
  "faisons la queue": "expression",
  "ont l'air": "expression",
  "ai l'impression": "expression",
  "avons l'intention": "expression",
  "La réussite": "...",
  "il faut faire attention": "expression",
  "de ne pas en parler": "parler",
  "de nouveau": "adjectif",
  "de parfait": "adjectif",
  "décorée": "adjectif",
  "dehors": "adverbe",
  "demain": "adverbe",
  "Demain": "adverbe",
  "Depuis quand": "adverbe interrogatif",
  "dernière": "adjectif",
  "Desquelles": "pronom interrogatif",
  "Desquels": "pronom interrogatif",
  "dessus": "adverbe",
  "difficile": "adjectif",
  "dort-il": "dormir",
  "doucement": "adverbe",
  "élégamment": "adverbe",
  "elle est": "être",
  "en a": "avoir",
  "encore": "adverbe",
  "enfin": "adverbe",
  "enlève": "enlever",
  "ennuyeuse": "adjectif",
  "ensemble": "adverbe",
  "entière": "adjectif",
  "entre autres": "expression",
  "Est-ce qu'il travaille": "travailler",
  "Est-ce que tu prends": "prendre",
  "Étiez-vous": "être",
  "Évidemment": "adverbe",
  "Exactement": "adverbe",
  "explique": "expliquer",
  "exposés": "exposer",
  "exprès": "adverbe",
  "extrèmement": "adverbe",
  "fatals": "adjectif",
  "fatigués": "adjectif",
  "fermée": "adjectif",
  "fières": "adjectif",
  "fraîche": "adjectif",
  "française": "adjectif",
  "françaises": "adjectif",
  "fréquemment": "adverbe",
  "généraux": "adjectif",
  "gentiment": "adverbe",
  "grand": "adjectif",
  "grande": "adjectif",
  "grises": "adjectif",
  "gros": "adjectif",
  "guère": "négation",
  "guère d'": "négation",
  "habites": "habiter",
  "heureusement": "adverbe",
  "heureuses": "adjectif",
  "ici": "adverbe",
  "il est": "être",
  "il reviendra": "revenir",
  "il y a": "expression",
  "Ils sont": "être",
  "intéressante": "adjectif",
  "invites": "inviter",
  "italienne": "adjectif",
  "italiennes": "adjectif",
  "J'ai bien": "avoir",
  "j'ai mis": "mettre",
  "J'en": "pronom",
  "jamais": "adverbe",
  "jamais rien": "négation",
  "Je l'": "pronom",
  "Je les": "pronom",
  "Je les y": "pronom",
  "Je leur en": "pronom",
  "Je lui": "pronom",
  "je n'ai": "avoir",
  "Je n'ai": "avoir",
  "Je n'ai pas": "avoir",
  "je n'ai rien": "avoir",
  "Je n'ai vu": "voir",
  "Je te": "pronom",
  "joueront-ils": "jouer",
  "jumeaux": "adjectif",
  "l'autre": "pronom indéfini",
  "L'un": "pronom indéfini",
  "l'un l'autre": "pronom indéfini",
  "l'un sans l'autre": "pronom indéfini",
  "La leur": "pronom",
  "la meilleure": "superlatif",
  "la même": "pronom indéfini",
  "la mienne": "pronom",
  "la moins lourde": "superlatif",
  "la nôtre": "pronom",
  "la plus belle": "superlatif",
  "la plus élégante": "superlatif",
  "la plus grande vallée": "superlatif",
  "la plus longue": "superlatif",
  "la plus mauvaise": "adjectif",
  "la tête": "nom",
  "la tienne": "pronom",
  "la vôtre": "pronom",
  "Laquelle": "pronom interrogatif",
  "le chinois": "nom",
  "le front": "nom",
  "le jour le plus long": "superlatif",
  "le leur": "pronom",
  "le meilleur": "superlatif",
  "le même": "pronom indéfini",
  "le mien": "pronom",
  "le mieux": "superlatif",
  "le moins": "superlatif",
  "le moins cher": "superlatif",
  "le moins du monde": "expression",
  "le plat le plus copieux": "superlatif",
  "le plus": "superlatif",
  "le plus beau numéro": "superlatif",
  "le plus haut": "superlatif",
  "le sien": "pronom",
  "le tien": "pronom",
  "le vôtre": "pronom",
  "légère": "adjectif",
  "lentement": "adverbe",
  "Lequel": "pronom interrogatif",
  "les autres": "pronom indéfini",
  "les leurs": "pronom",
  "les meilleures": "superlatif",
  "les mêmes": "pronom indéfini",
  "les miennes": "pronom",
  "les miens": "pronom",
  "les moins rapides": "superlatif",
  "les nôtres": "pronom",
  "les plus délicieux": "superlatif",
  "les plus étroites": "superlatif",
  "les siennes": "pronom",
  "les siens": "pronom",
  "les uns après les autres": "pronom indéfini",
  "les vôtres": "pronom",
  "Lesquelles": "pronom interrogatif",
  "Lesquels": "pronom interrogatif",
  "leurs": "déterminant",
  "longue": "adjectif",
  "Lui aussi": "expression",
  "m'en": "pronom",
  "m'y": "pronom",
  "Mange-t-elle": "manger",
  "marron": "adjectif",
  "méchamment": "adverbe",
  "meilleur": "adjectif",
  "meilleure": "adjectif",
  "meilleures": "adjectif",
  "mieux": "adverbe",
  "mieux comprendre": "comprendre",
  "Moi aussi": "expression",
  "Moi non plus": "expression",
  "moins cher": "comparatif",
  "moins confortables": "comparatif",
  "moins précise": "comparatif",
  "mon": "déterminant",
  "mortelle": "adjectif",
  "moyenne": "adjectif",
  "n'": "négation",
  "n'a": "avoir",
  "n'a plus": "avoir",
  "n'achètes que": "acheter",
  "n'aimais pas": "aimer",
  "n'as": "avoir",
  "n'as revu personne": "revoir",
  "n'avais rien": "avoir",
  "n'avez reçu personne": "recevoir",
  "n'avions joint personne": "joindre",
  "n'avons jamais": "avoir",
  "n'écoute que": "écouter",
  "n'êtes plus": "être",
  "n'habite plus": "habiter",
  "n'importe laquelle": "pronom indéfini",
  "n'importe lequel": "pronom indéfini",
  "n'importe lesquelles": "pronom indéfini",
  "n'importe lesquels": "pronom indéfini",
  "n'importe quoi": "pronom indéfini",
  "nationaux": "adjectif",
  "naturelle": "adjectif",
  "ne": "négation",
  "ne bois que": "boire",
  "ne connaît": "connaître",
  "ne fait": "faire",
  "ne jamais mentir": "mentir",
  "Ne l'appelle": "appeler",
  "ne pas": "négation",
  "ne pas bien parler": "parler",
  "ne pas fumer": "fumer",
  "ne plus": "négation",
  "ne plus prendre": "prendre",
  "ne rien dire": "dire",
  "ne s'est pas": "être",
  "Ne sait-il pas": "savoir",
  "ne se lève pas": "se lever",
  "ne travaillera": "travailler",
  "ne vais pas": "aller",
  "neuve": "adjectif",
  "ni": "négation",
  "non": "adverbe",
  "Non merci": "expression",
  "non plus": "adverbe",
  "Non seulement": "expression",
  "normales": "adjectif",
  "nouveaux": "adjectif",
  "nouvel": "adjectif",
  "nouvelle": "adjectif",
  "nulle part": "adverbe",
  "nulle part ailleurs": "adverbe",
  "orange": "adjectif",
  "Où": "pronom interrogatif",
  "Où est-ce qu'elle va": "aller",
  "Oui": "adverbe",
  "par": "préposition",
  "Par": "préposition",
  "Parce que": "conjonction",
  "pareille": "adjectif",
  "Parfois": "adverbe",
  "particulièrement": "adverbe",
  "passionnante": "adjectif",
  "patiemment": "adverbe",
  "pauvre": "adjectif",
  "pendant": "préposition",
  "Personne": "pronom indéfini",
  "personne d'autre": "pronom indéfini",
  "personne n'": "pronom indéfini",
  "personne n'est": "être",
  "petit": "adjectif",
  "petites": "adjectif",
  "petits": "adjectif",
  "peu": "adverbe",
  "Peut-elle": "pouvoir",
  "pire": "adjectif",
  "pires": "adjectif",
  "plus": "négation",
  "plus d'": "comparatif",
  "plus de": "comparatif",
  "plus doucement": "comparatif",
  "plus grande": "comparatif",
  "plus jamais": "négation",
  "plus lourd": "comparatif",
  "plus mal": "adverbe",
  "plus mauvaise": "adjectif",
  "plus mauvaises": "adjectif",
  "plus prudemment": "comparatif",
  "plus que": "comparatif",
  "plus rapide": "comparatif",
  "plus rapidement": "comparatif",
  "plus rien": "négation",
  "plus soigneusement": "comparatif",
  "plus vite": "comparatif",
  "plusieurs": "pronom indéfini",
  "pour": "préposition",
  "pour quoi": "pronom interrogatif",
  "pourquoi": "adverbe interrogatif",
  "Pourquoi": "adverbe interrogatif",
  "Pourquoi est-ce que tu rentres": "rentrer",
  "Pourra-t-elle": "pouvoir",
  "précisément": "adverbe",
  "première": "adjectif",
  "pressés": "adjectif",
  "propre": "adjectif",
  "prudemment": "adverbe",
  "Puis-je": "pouvoir",
  "qu'": "conjonction",
  "Qu'": "pronom interrogatif",
  "qu'elle": "comparatif",
  "Qu'est-ce que": "pronom interrogatif",
  "Qu'est-ce que tu fais": "faire",
  "Qu'est-ce qui": "pronom interrogatif",
  "qu'eux": "comparatif",
  "quand": "adverbe interrogatif",
  "Quand": "adverbe interrogatif",
  "Que": "pronom interrogatif",
  "que ça": "pronom",
  "que moi": "comparatif",
  "que nous avons fait": "faire",
  "Quel": "déterminant",
  "Quelle": "déterminant",
  "quelle heure": "expression",
  "Quelles": "déterminant",
  "quelqu'un": "pronom indéfini",
  "Quelqu'un": "pronom indéfini",
  "quelque chose": "pronom indéfini",
  "quelques-unes": "pronom indéfini",
  "Quelques-unes": "pronom indéfini",
  "quelques-uns": "pronom indéfini",
  "Quels": "déterminant",
  "Qui": "pronom interrogatif",
  "Qui est-ce que": "pronom interrogatif",
  "Qui est-ce qui": "pronom interrogatif",
  "qui pis est": "expression",
  "quoi": "pronom interrogatif",
  "Quoi": "pronom interrogatif",
  "quotidienne": "adjectif",
  "rarement": "adverbe",
  "réelle": "adjectif",
  "Répond-il": "répondre",
  "restées": "rester",
  "rien": "pronom indéfini",
  "Rien": "pronom indéfini",
  "rien d'autre": "pronom indéfini",
  "rien n'a": "avoir",
  "rien ne": "pronom indéfini",
  "Rien ne": "pronom indéfini",
  "ronds": "adjectif",
  "roses": "adjectif",
  "rouges": "adjectif",
  "russe": "adjectif",
  "sa": "déterminant",
  "sais": "savoir",
  "sales": "adjectif",
  "sans": "préposition",
  "Sans doute": "adverbe",
  "saura-t-elle": "savoir",
  "se retrouve": "se retrouver",
  "sereins": "adjectif",
  "sérieuse": "adjectif",
  "sérieusement": "adverbe",
  "ses": "déterminant",
  "seul": "adjectif",
  "si": "conjonction",
  "Si": "adverbe",
  "si tu viens": "conjonction",
  "Si, j'en ai goûté": "expression",
  "Si, je le connais": "expression",
  "Si, si": "expression",
  "sociales": "adjectif",
  "son": "déterminant",
  "sont-elles": "être",
  "souvent": "adverbe",
  "sportives": "adjectif",
  "suédois": "adjectif",
  "suffisamment": "adverbe",
  "sur": "préposition",
  "Tant pis": "expression",
  "téléphonera-t-il": "téléphoner",
  "terriblement": "adverbe",
  "tient": "tenir",
  "tôt": "adverbe",
  "tous": "pronom indéfini",
  "Tous": "pronom indéfini",
  "tout": "pronom indéfini",
  "Tout": "pronom indéfini",
  "tout le monde": "pronom indéfini",
  "toute": "pronom indéfini",
  "toutes": "pronom indéfini",
  "Toutes": "pronom indéfini",
  "très": "adverbe",
  "trop": "adverbe",
  "tu ouvres": "ouvrir",
  "un certain": "déterminant",
  "un meilleur": "adjectif",
  "une autre fois": "expression",
  "Va-t-on": "aller",
  "vais rien": "aller",
  "vert foncé": "adjectif",
  "viande": "nom",
  "vieille": "adjectif",
  "Viens-tu": "venir",
  "vifs": "adjectif",
  "vite": "adverbe",
  "vite revenir": "revenir",
  "vos propres": "déterminant",
  "voteront-ils": "voter",
  "vraiment": "adverbe",
  "vraiment savoir": "savoir",
  // Sections 21-24 (hypothèses, discours indirect, voix passive, connecteurs)
  "a avoué": "avouer",
  "À cause de": "locution prépositive",
  "à cause de la": "locution prépositive",
  "a été arrêté": "arrêter",
  "a été inaugurée": "inaugurer",
  "a été nettoyée": "nettoyer",
  "a été soigné": "soigner",
  "a été surveillé": "surveiller",
  "a été votée": "voter",
  "a plu": "pleuvoir",
  "a volé": "voler",
  "accorde": "accorder",
  "action": "nom",
  "aient": "avoir",
  "aillent": "aller",
  "Alors": "conjonction",
  "annoncé": "annoncer",
  "annoncés": "annoncer",
  "arrêté": "arrêter",
  "arrivait": "arriver",
  "assez": "adverbe",
  "auraient préféré": "préférer",
  "auraient pris": "prendre",
  "auraient rangé": "ranger",
  "aurait expédié": "expédier",
  "aurait trouvé": "trouver",
  "aurait voulu": "vouloir",
  "auriez su": "savoir",
  "aurions achevé": "achever",
  "auront": "avoir",
  "Aussi": "conjonction",
  "avaient saisi": "saisir",
  "avait rangé": "ranger",
  "avait reçu": "recevoir",
  "avait respecté": "respecter",
  "avait visité": "visiter",
  "avez souri": "sourire à",
  "aviez dit": "dire",
  "avions commandé": "commander",
  "avons marché": "marcher",
  "avons répondu": "répondre à",
  "avons vendu": "vendre",
  "but": "nom",
  "C'est pourquoi": "locution conjonctive",
  "car": "conjonction",
  "ce jour-là": "expression temporelle",
  "cependant": "adverbe",
  "ces jours-là": "expression temporelle",
  "Comme": "conjonction",
  "comprennes": "comprendre",
  "connaissions": "connaître",
  "conséquence": "nom",
  "construite": "construire",
  "coupées": "couper",
  "d'éteindre": "éteindre",
  "de chuchoter": "chuchoter",
  "de ne pas courir": "courir",
  "de respirer": "respirer",
  "de téléphoner": "téléphoner",
  "décerne": "décerner",
  "déclenche": "déclencher",
  "découvriraient": "découvrir",
  "défendu": "défendre",
  "deux jours plus tôt": "expression temporelle",
  "donc": "conjonction",
  "Donc": "conjonction",
  "dormez": "dormir",
  "Du coup": "locution conjonctive",
  "économiserions": "économiser",
  "écrivais": "écrire",
  "elle": "pronom",
  "elle est partie": "partir",
  "elles": "pronom",
  "en cas de": "locution prépositive",
  "en dépit de": "locution prépositive",
  "En raison": "locution prépositive",
  "en raison d'une": "locution prépositive",
  "enseigne": "enseigner",
  "est arrivé": "arriver",
  "est fermée": "fermer",
  "est imprimée": "imprimer",
  "est lavé": "laver",
  "est né": "naître",
  "est ouverte": "ouvrir",
  "est préparé": "préparer",
  "étaient construites": "construire",
  "étaient cultivées": "cultiver",
  "étaient prises": "prendre",
  "était applaudie": "applaudir",
  "était emporté": "emporter",
  "était érodée": "éroder",
  "était interdit": "interdire",
  "Étant donné que": "locution conjonctive",
  "état": "nom",
  "été": "être",
  "étions aidés": "aider",
  "étions restés": "rester",
  "faute": "locution prépositive",
  "fermait": "fermer",
  "gagnions": "gagner",
  "grâce à": "locution prépositive",
  "grâce au": "locution prépositive",
  "ils": "pronom",
  "interdit": "interdire",
  "interrogé": "interroger",
  "j'avais écouté": "écouter",
  "je": "pronom",
  "jouerait": "jouer",
  "la semaine suivante": "expression temporelle",
  "la veille": "expression temporelle",
  "le lendemain": "expression temporelle",
  "louaient": "louer",
  "ma": "déterminant",
  "mais": "conjonction",
  "malgré": "préposition",
  "Malgré": "préposition",
  "Malgré le fait de": "locution prépositive",
  "Malgré le fait que": "locution conjonctive",
  "mangeront": "manger",
  "me suis fait": "se faire",
  "même si": "conjonction",
  "monter": "infinitif",
  "j'aie": "avoir",
  "j'aille": "aller",
  "je rentrais": "rentrer",
  "que ce jour-là": "expression temporelle",
  "que ces jours-là": "expression temporelle",
  "nageaient": "nager",
  "ne se dit": "se dire",
  "ne se fait": "se faire",
  "néanmoins": "adverbe",
  "nettoyée": "nettoyer",
  "nommée": "nommer",
  "nous étions inscrits": "s'inscrire",
  "on": "pronom indéfini",
  "ont acheté": "acheter",
  "ont été": "être",
  "ont été construits": "construire",
  "ont été vendues": "vendre",
  "ont pensé": "penser à",
  "ouverte": "ouvrir",
  "ouvre": "ouvrir",
  "Par conséquent": "locution conjonctive",
  "parce qu'": "conjonction",
  "parce que": "conjonction",
  "partira": "partir",
  "passerons": "passer",
  "perdrais": "perdre",
  "pleuvait": "pleuvoir",
  "posées": "poser",
  "pour que": "locution conjonctive",
  "pourtant": "adverbe",
  "pourvu que": "locution conjonctive",
  "pouvaient": "pouvoir",
  "prendrez": "prendre",
  "prétendait": "prétendre",
  "prévenu": "prévenir",
  "promets": "promettre",
  "publiés": "publier",
  "Puisque": "conjonction",
  "punis": "punir",
  "qu'elles": "conjonction + pronom sujet",
  "qu'il": "conjonction + pronom sujet",
  "qu'il connaît": "conjonction + connaître au présent",
  "quittez": "quitter",
  "racontés": "raconter",
  "recevrais": "recevoir",
  "reconnaît": "reconnaître",
  "refassent": "refaire",
  "rentrais": "rentrer",
  "réparaient": "réparer",
  "répond": "répondre",
  "répondra": "répondre",
  "réserves": "réserver",
  "révisiez": "réviser",
  "risquez": "risquer",
  "s'est fait": "se faire",
  "sachent": "savoir",
  "savent": "savoir",
  "se boit": "se boire",
  "se conservent": "se conserver",
  "se couvre": "se couvrir",
  "se démonte": "se démonter",
  "sera annulé": "annuler",
  "sera envoyée": "envoyer",
  "sera inaugurée": "inaugurer",
  "serait rentrée": "rentrer",
  "seriez entrés": "entrer",
  "seront annoncés": "annoncer",
  "sert": "servir",
  "si on veut": "expression",
  "signé": "signer",
  "sinon": "adverbe",
  "sont accueillis": "accueillir",
  "sont éteintes": "éteindre",
  "sont évalués": "évaluer",
  "sont parties": "partir",
  "sont triés": "trier",
  "sont venues": "venir",
  "suis observé": "observer",
  "tant": "adverbe",
  "tellement": "adverbe",
  "tellement de": "adverbe + préposition",
  "toutefois": "adverbe",
  "traduit": "traduire",
  "tu habites": "habiter",
  "venaient": "venir",
  "vendues": "vendre",
  "visitaient": "visiter",
  "visiteriez": "visiter",
  "visiterions": "visiter",
  "visitiez": "visiter",
  "vous êtes fait": "se faire",
  "vous finissez": "finir",
  "Vu que": "locution conjonctive",
  // Sections 25-28 (expression du temps, gérondif, gallicismes, accord du participe passé)
  "a applaudi": "applaudir",
  "À chaque": "préposition + déterminant",
  "à cuisiner": "cuisiner",
  "a déposé": "déposer",
  "À partir de": "locution prépositive",
  "à skier": "skier",
  "acheté": "s'acheter",
  "achetées": "acheter",
  "allant": "aller",
  "allée": "aller",
  "Alors que": "locution conjonctive",
  "amusante": "amuser",
  "après": "préposition",
  "Après": "préposition",
  "arrivant": "arriver",
  "arrivé": "arriver",
  "atteindre": "infinitif",
  "attendues": "attendre",
  "Au moment où": "locution conjonctive",
  "augmentent": "augmenter",
  "Avant": "préposition",
  "avant que": "locution conjonctive",
  "après que": "locution conjonctive",
  "avoir fait": "faire",
  "Ayant caché": "cacher",
  "Ayant fait": "faire",
  "Ayant fini": "finir",
  "Ayant oublié": "oublier",
  "Ayant préparé": "préparer",
  "Ayant rangé": "ranger",
  "battant": "battre",
  "buvant": "boire",
  "changer": "infinitif",
  "Chaque fois que": "locution conjonctive",
  "choisie": "choisir",
  "commençant": "commencer",
  "Connaissant": "connaître",
  "connues": "se connaître",
  "construit": "construire",
  "Contemplant": "contempler",
  "convaincant": "convaincre",
  "convaincante": "convaincre",
  "couchant": "se coucher",
  "coupé": "se couper",
  "courant": "courir",
  "claquant": "claquer",
  "criant": "crier",
  "jardinant": "jardiner",
  "observant": "observer",
  "chantant": "chanter",
  "regardant": "regarder",
  "sautant": "sauter",
  "allons manger": "manger",
  "allons arriver": "arriver",
  "ne viens pas de": "venir",
  "ne venez pas de": "venir",
  "ne viennent pas de": "venir",
  "ne viens pas": "venir",
  "ne viens de pas": "venir",
  "ne venez de pas": "venir",
  "ne vas pas de": "aller",
  "ne venons pas de": "venir",
  "ne viennent pas d'": "venir",
  "ne vont pas d'": "aller",
  "ne viens pas d'": "venir",
  "ne venons de pas": "venir",
  "venais d'": "venir",
  "venez de": "venir",
  "vient de": "venir",
  "fredonnant": "fredonner",
  "coûté": "coûter",
  "coûtés": "coûter",
  "cuisinant": "cuisiner",
  "cuisinons": "cuisiner",
  "Dans": "préposition",
  "de le": "pronom COD",
  "te les": "pronoms COI + COD",
  "de le lui": "pronom COD + COI",

  "de me les": "pronoms COI + COD",
  "de les": "pronom COD",
  "de lui": "pronom COI",
  "de s'": "pronom réfléchi",
  "est en train de faire": "être + en train de + faire",
"sont en train de finir": "être + en train de + finir",
"est en train de": "être",
  "vais t'envoyer": "aller + envoyer",
  "ne sont jamais": "être",
  "n'est plus": "être",
  "suis ne pas": "être",
  "ne pas suis": "être",
  "suis pas": "être",
  "ne suis pas de": "être",
  "est plus": "être",
  "n'est pas jamais": "être",
  "n'est pas de": "être",
  "ne sont pas jamais": "être",
  "sont jamais": "être",
  "ne sont jamais de": "être",
  "sommes en train de": "être",
  "êtes en train de": "être",
  "êtes en train d'": "être",
  "étions en train de": "être",
  "étaient en train de": "être",
  "était en train de": "être",
  "étiez en train de": "être",
  "étions en train à": "être",
  "étions train de": "être",
  "es en train de": "être",
  "es en train à": "être",
  "es train de": "être",
  "es en train": "être",
  "sommes en train à": "être",
  "sommes train de": "être",
  "sont en train de": "être",
  "est en train à": "être",
  "est train de": "être",
  "de te les": "pronom réfléchi + COD",
  "défilant": "défiler",
  "depuis": "préposition",
  "depuis que": "conjonction",
  "Depuis": "préposition",
  "Depuis que": "locution conjonctive",
  "dès": "préposition",
  "dès que": "locution conjonctive",
  "seras rentré": "rentrer",
  "la lecture": "lire",
  "la proclamation": "proclamer",
  "Dès": "préposition",
  "Dès que": "locution conjonctive",
  "deviendra": "devenir",
  "dévorant": "dévorer",
  "différant": "différer",
  "dormaient": "dormir",
  "sommes rencontrés": "se rencontrer",
  "suis retourné": "se retourner",
  "s'est retourné": "se retourner",
  "a acheté": "acheter",
  "est montée": "monter",
  "duré": "durer",
  "éblouissantes": "éblouir",
  "écoulés": "s'écouler",
  "écoutant": "écouter",
  "écoutées": "écouter",
  "écrite": "écrire",
  "En allant": "aller",
  "En chantant": "chanter",
  "en écoutant": "écouter",
  "En écoutant": "écouter",
  "En étant": "être",
  "en faisant": "faire",
  "En fredonnant": "fredonner",
  "en lisant": "lire",
  "en mangeant": "manger",
  "en marchant": "marcher",
  "En nous levant": "se lever",
  "En te levant": "se lever",
  "En te dépêchant": "se dépêcher",
  "en promenant": "promener",
  "En révisant": "réviser",
  "En sachant": "savoir",
  "en sachant": "savoir",
  "en arrivant": "arriver",
  "en étant": "être",
  "En vous levant": "se lever",
  "En ouvrant": "ouvrir",
  "en ouvrant": "ouvrir",
  "En finissant": "finir",
  "La nuit tombant sur la ville": "tomber",
  "augmentant": "augmenter",
  "sortant": "sortir",
  "à laver": "laver",
  "en skiant": "skier",
  "en cuisinant": "cuisiner",
  "fatigants": "fatiguer",
  "provoquant": "provoquer",
  "provocantes": "provoquer",
  "en soupirant": "soupirer",
  "en souriant": "sourire",
  "En téléphonant": "téléphoner",
  "en train de": "locution",
  "en travaillant": "travailler",
  "En travaillant": "travailler",
  "en voyageant": "voyager",
  "enfuis": "s'enfuir",
  "entendu": "entendre",
  "entendue": "entendre",
  "envahissant": "envahir",
  "es en train de dormir": "être",
  "étant": "être",
  "Étant": "être",
  "Étant arrivée": "arriver",
  "Étant sortis": "sortir",
  "Étant venus": "venir",
  "êtes en train de regarder": "être",
  "être rentrés": "rentrer",
  "être sortie": "sortir",
  "évaluant": "évaluer",
  "évanouie": "s'évanouir",
  "expliquant": "expliquer",
  "faisant": "faire",
  "fatigant": "fatiguer",
  "fatiguant": "fatiguer",
  "fermant": "fermer",
  "Finissant": "finir",
  "grondant": "gronder",
  "habitent": "habiter",
  "Il y a": "expression temporelle",
  "imprimés": "imprimer",
  "interprétées": "interpréter",
  "jardiner": "infinitif",
  "joues": "jouer",
  "jouez": "jouer",
  "jusqu'à": "préposition",
  "jusqu'à ce que": "locution conjonctive",
  "jusque-là": "adverbe",
  "laissé": "laisser",
  "laissés": "laisser",
  "lavé": "se laver",
  "laves": "laver",
  "le policier": "nom",
  "levées": "se lever",
  "louée": "se louer",
  "mangeant": "manger",
  "Mangeant": "manger",
  "marchions": "marcher",
  "méfiées": "se méfier",
  "mises": "mettre",
  "montré": "montrer",
  "n'allez pas": "aller",
  "n'allons pas": "aller",
  "n'as pas perdu": "perdre",
  "ne suis pas": "être",
  "sommes pas": "être",
  "ne sommes pas": "être",
  "n'est plus pas": "être",
  "ne va jamais": "aller",
  "ne venons pas": "venir",
  "ne vient pas de": "venir",
  "ne vont plus": "aller",
  "née": "naître",
  "Nous allons": "aller",
  "obéissants": "obéir",
  "ont annoncé": "annoncer",
  "ont reçu": "recevoir",
  "a soutenu": "soutenir",
  "ont fini": "finir",
  "ouvertes": "s'ouvrir",
  "par s'excuser": "s'excuser",
  "pas": "adverbe de négation",
  "passé": "se passer",
  "Pendant": "préposition",
  "pendant que": "locution conjonctive",
  "roulait": "rouler",
  "fume": "fumer",
  "travaillais": "travailler",
  "a joué": "jouer",
  "Pendant que": "locution conjonctive",
  "Pendant que je faisais": "faire",
  "Pendant que les enfants s'endormaient": "s'endormir",
  "pesé": "peser",
  "portant": "porter",
  "poussant": "pousser",
  "prennent": "prendre",
  "préparant": "préparer",
  "préparées": "préparer",
  "promenée": "se promener",
  "provocant": "provoquer",
  "que je t'ai achetés": "acheter",
  "rédigeait": "rédiger",
  "regardée": "regarder",
  "regardées": "se regarder",
  "régné": "régner",
  "remarqueras": "remarquer",
  "rendu compte": "se rendre compte",
  "répandue": "se répandre",
  "révises": "réviser",
  "roulant": "rouler",
  "s'en": "s'en aller",
  "s'endorme": "s'endormir",
  "s'étant abattue": "s'abattre",
  "S'étant couchées": "se coucher",
  "S'étant dépêchée": "se dépêcher",
  "S'étant levée": "se lever",
  "S'étant abattue": "s'abattre",
  "montant": "monter",
  "sachant": "savoir",
  "Sachant": "savoir",
  "se": "pronom réfléchi",
  "se sont téléphoné": "se téléphoner",
  "serrant": "serrer",
  "sommes en train de préparer": "être",
  "sonnant": "sonner",
  "sont en train de jouer": "être",
  "souriant": "sourire",
  "souvenue": "se souvenir",
  "suis en train de conduire": "être",
  "suivant": "suivre",
  "t'entraînant": "s'entraîner",
  "Tandis que": "locution conjonctive",
  "téléphoné": "téléphoner",
  "tombant": "tomber",
  "tombé": "tomber",
  "tombées": "tomber",
  "Tout en mettant": "mettre",
  "Tout en réparant": "réparer",
  "Tout en sachant": "savoir",
  "travaillions": "travailler",
  "Tu vas": "aller",
  "va commencer": "commencer",
  "vais rester": "rester",
  "valus": "valoir",
  "vécu": "vivre",
  "vécues": "vivre",
  "vendant": "vendre",
  "venez d'": "venir",
  "venons": "venir",
  "venons de": "venir",
  "venues": "venir",
  "viennent": "venir",
  "viennent de": "venir",
  "viens de": "venir",
  "vient d'": "venir",
  "visités": "visiter",
  "vivent": "vivre",
  "vous la": "pronom",
  "vous levant": "se lever",
  "Voyant": "voir",
  "vue": "voir",
  "vues": "voir",
};

// 09-19 INPUT questions use descriptive hints (not just the infinitive)
// since the answer literally is the infinitive form.
export const hintAliases: Record<string, Set<string>> = {
  "fatigants": new Set(["fatiguer", "l'adjectif verbal de « fatiguer »"]),
  "fatiguant": new Set(["fatiguer", "le participe présent de « fatiguer »"]),
  "différant": new Set(["différer", "le participe présent de « différer »"]),
  "provoquant": new Set(["provoquer", "le participe présent de « provoquer »"]),
  "provocantes": new Set(["provoquer", "l'adjectif verbal de « provoquer »"]),
  "Le soleil se levant à peine": new Set(["se lever"]),
  "La nuit tombant sur la ville": new Set(["tomber", "le participe présent de « tomber »"]),

  "Chaque fois que": new Set(["locution conjonctive", "locution conjonctive de trois mots", "locution conjonctive de trois mots commençant par « chaque »"]),
  "En te dépêchant": new Set(["se dépêcher", "le gérondif de « se dépêcher »"]),
  "Pendant que": new Set(["locution conjonctive", "locution conjonctive de deux mots commençant par « pendant »"]),
  "jusqu'à ce que": new Set(["locution conjonctive", "locution conjonctive de trois mots commençant par « jusqu »"]),
  "est": new Set(["être", "être (présent)"]),
  "où": new Set(["pronom relatif", "conjonction"]),
  "a applaudi": new Set(["applaudir", "applaudir (passé composé)"]),
  "acheter": new Set(["acheter", "forme infinitive du verbe conjugué"]),
  "Laver": new Set(["laver", "forme infinitive du verbe conjugué"]),
  "Agiter": new Set(["agiter", "forme infinitive du verbe conjugué"]),
  "Conserver": new Set(["conserver", "forme infinitive du verbe conjugué"]),
  "Ne pas exposer": new Set(["exposer", "ne pas + infinitif du verbe conjugué"]),
  "Ne pas laisser": new Set(["laisser", "ne pas + infinitif du verbe conjugué"]),
  // 09-20 INPUT questions use compound hints showing verb + pronouns.
  "Donne-le-moi": new Set(["donner", "donner + le + moi"]),
  "Apporte-la-moi": new Set(["apporter", "apporter + la + moi"]),
  "Vas-y": new Set(["aller", "aller + y"]),
  "Donne-m'en": new Set(["donner", "donner + moi + en"]),
  "la": new Set(["...", "pronom COD pour « cette photo »", "article défini", "article défini (préférence)", "article", "pronom COD"]),
  "des": new Set(["article", "article indéfini pluriel"]),
  // 10-14 INPUT questions use "article défini" as hint for definite-article answers.
  "le": new Set(["...", "article défini"]),
  "les": new Set(["...", "article défini"]),
  "La": new Set(["...", "article défini", "article"]),
  "Les": new Set(["...", "article défini"]),
  "Le": new Set(["...", "article défini"]),
  // 10-18 INPUT questions use disambiguating hints naming the expression's key noun.
  "faisons la queue": new Set(["expression", "expression avec « queue »"]),
  "ont l'air": new Set(["expression", "expression avec « air »", "expression figée « avoir l'air »"]),
  "ai l'impression": new Set(["expression", "expression avec « impression »"]),
  "auras l'occasion": new Set(["avoir", "expression avec « occasion »", "expression avec « avoir » et « occasion »", "expression figée « avoir l'occasion » (futur)"]),
  "avons l'intention": new Set(["expression", "expression avec « intention »"]),
  // 25-03 INPUT question uses "locution conjonctive" as hint for "depuis que".
  "depuis que": new Set(["conjonction", "locution conjonctive"]),
  // 25-04 INPUT question uses "expression temporelle" as hint for "il y a".
  "il y a": new Set(["expression", "expression temporelle"]),
  // 25-05 INPUT question uses "locution" as hint for "Il y a".
  "Il y a": new Set(["expression temporelle", "locution"]),
  // 25-04 INPUT question uses "conjonction" as hint for "que".
  // 27-11 uses "négation restrictive" for "que" (ne...que).
  "que": new Set(["pronom relatif", "conjonction", "négation restrictive"]),
  // 27-11 passé récent INPUT uses "venir" as hint for "de"/"d'".
  // 27-13 présent continu INPUT uses "préposition" as hint for "de".
  "de": new Set(["article", "venir", "préposition"]),
  "d'": new Set(["article", "venir", "passé récent"]),
  // 27-12 uses COD-pronoun hints for "de l'"/"de la" and pronoun hints for "le lui"/"te les".
  "de lui": new Set(["pronom COI", "de + pronom COI"]),
  "vous la": new Set(["pronom", "pronoms"]),
  "leur": new Set(["pronom", "pronom COI"]),
  "d'y": new Set(["pronom"]),
  "de leur": new Set(["pronom", "de + pronom COI"]),
  "est en train de": new Set(["être", "être + en train de"]),
  "est en train de faire": new Set(["être + en train de + faire", "en train de"]),
  "sont en train de finir": new Set(["être + en train de + finir", "en train de"]),
  "sommes en train de": new Set(["être", "être + en train de"]),
  "es en train de": new Set(["être", "être + en train de"]),
  "êtes en train de": new Set(["être", "être + en train de"]),
  "sont en train de": new Set(["être", "être + en train de"]),
  "êtes en train d'": new Set(["être", "être + en train de"]),
  "étions en train de": new Set(["être", "être + en train de"]),
  "étaient en train de": new Set(["être", "être + en train de"]),
  "était en train de": new Set(["être", "être + en train de"]),
  "étiez en train de": new Set(["être", "être + en train de"]),
  "étions en train à": new Set(["être", "être + en train de"]),
  "étions train de": new Set(["être", "être + en train de"]),
  "est en train à": new Set(["être", "être + en train de"]),
  "est train de": new Set(["être", "être + en train de"]),
  "de l'": new Set(["article", "pronom COD"]),
  "de la": new Set(["préposition", "pronom COD"]),
  "le lui": new Set(["pronom", "pronom COD + COI"]),
  // 25-08 INPUT questions use "préposition" as hint for "en".
  "en": new Set(["pronom", "préposition", "préposition de deux lettres"]),
};

export type AnswerHintKey = keyof typeof answerHints;
