// Answer-to-hint dictionary for FR
// Hints follow these rules:
// - Verbs: dictionary form (infinitive)
// - Articles: "article"
// - Pronouns: "pronom"
// - Other words: word type in French

export const answerHints: Record<string, string> = {
  "aboieront": "aboyer",
  "'irons jamais": "aller",
  "a": "avoir",
  "A-t-il": "avoir",
  "A-t-il compris": "comprendre",
  "As-tu": "avoir",
  "As-tu compris": "comprendre",
  "a fait": "faire",
  "a été": "être",
  "a grandi": "grandir",
  "a habité": "habiter",
  "à laquelle": "pronom relatif",
  "à leurs parents": "préposition",
  "a lu": "lire",
  "à ma meilleure amie": "préposition",
  "a marché": "marcher",
  "a mis": "mettre",
  "à mon ami": "préposition",
  "a monté": "monter",
  "à nos élèves": "préposition",
  "a reçu": "recevoir",
  "a sonné": "sonner",
  "a su": "savoir",
  "à ta grand-mère": "préposition",
  "a terminé": "terminer",
  "a rédigé": "rédiger",
  "a couru": "courir",
  "a peint": "peindre",
  "a fini": "finir",
  "a rempli": "remplir",
  "a raté": "rater",
  "a obtenu": "obtenir",
  "construisait": "construire",
  "pratiquait": "pratiquer",
  "se rendait": "se rendre",
  "organiserons": "organiser",
  "ont organisé": "organiser",
  "s'est ouverte": "s'ouvrir",
  "skiait": "skier",
  "cuisait": "cuire",
  "cultiverait": "cultiver",
  "cultiverions": "cultiver",
  "cessera": "cesser",
  "racontait": "raconter",
  "réserveront": "réserver",
  "s'est levé": "se lever",
  "achetée": "acheter",
  "achètes": "acheter",
  "acquerras": "acquérir",
  "agissez": "agir",
  "Agiter": "agiter",
  "ai": "avoir",
  "a perdu": "perdre",
  "a oublié": "oublier",
  "avons terminé": "terminer",
  "avons rédigé": "rédiger",
  "avons refait": "refaire",
  "avons visité": "visiter",
  "visiterez": "visiter",
  "rentrerons": "rentrer",
  "rentrerez": "rentrer",
  "est allé": "aller",
  "a disparu": "disparaître",
  "a pris": "prendre",
  "ont brisé": "briser",
  "ont préparé": "préparer",
  "préparerez": "préparer",
  "ont marché": "marcher",
  "est tombée": "tomber",
  "est tombé": "tomber",
  "est devenu": "devenir",
  "est devenue": "devenir",
  "brûlait": "brûler",
  "murmurait": "murmurer",
  "a apporté": "apporter",
  "nageait": "nager",
  "déjeunions": "déjeuner",
  "écrivait": "écrire",
  "écrives": "écrire",
  "écrive": "écrire",
  "écriras": "écrire",
  "écrirais": "écrire",
  "écrirait": "écrire",
  "buvait": "boire",
  "ai bu": "boire",
  "a mangé": "manger",
  "a compris": "comprendre",
  "a entendu": "entendre",
  "ont entendu": "entendre",
  "ont observé": "observer",
  "a éteint": "éteindre",
  "suis sorti": "sortir",
  "sommes arrivés": "arriver",
  "sommes installés": "installer",
  "est revenu": "revenir",
  "avons brisé": "briser",
  "avons perdu": "perdre",
  "a rangé": "ranger",
  "a signé": "signer",
  "avons traversé": "traverser",
  "ont commencé": "commencer",
  "a chanté": "chanter",
  "as peint": "peindre",
  "avons réparé": "réparer",
  "a allumé": "allumer",
  "ont changé": "changer",
  "a composé": "composer",
  "a trouvé": "trouver",
  "avez trouvé": "trouver",
  "ont chanté": "chanter",
  "as posé": "poser",
  "a fermé": "fermer",
  "avons raté": "rater",
  "a ouvert": "ouvrir",
  "a attrapé": "attraper",
  "a renversé": "renverser",
  "ont manqué": "manquer",
  "avons tourné": "tourner",
  "avons fermé": "fermer",
  "a laissé": "laisser",
  "avez oublié": "oublier",
  "avons regardé": "regarder",
  "ai fermé": "fermer",
  "aideras": "aider",
  "aie": "avoir",
  "Aie": "avoir",
  "aie fait": "faire",
  "aie prises": "prendre",
  "aie rencontrée": "rencontrer",
  "aient comprise": "comprendre",
  "aient fini": "finir",
  "aient réussi": "réussir",
  "aient résolu": "résoudre",
  "aies résolu": "résoudre",
  "aies saisi": "saisir",
  "ait résolu": "résoudre",
  "aient signé": "signer",
  "aient découvert": "découvrir",
  "ait découvert": "découvrir",
  "ait trahi": "trahir",
  "aient rendu": "rendre",
  "aient eu": "avoir",
  "aies acceptée": "accepter",
  "aies accepté": "accepter",
  "ayez manqué": "manquer",
  "aies compris": "comprendre",
  "aies comprise": "comprendre",
  "aies été": "être",
  "aies fini": "finir",
  "aies oublié": "oublier",
  "aies obtenu": "obtenir",
  "aies participé": "participer",
  "aies obtenue": "obtenir",
  "aies perdue": "perdre",
  "aies quitté": "quitter",
  "aies regardé": "regarder",
  "aies relevé": "relever",
  "aies suivi": "suivre",
  "aies tenu": "tenir",
  "aies tenue": "tenir",
  "aies vu": "voir",
  "aille": "aller",
  "ailles": "aller",
  "aimerais": "aimer",
  "aimerait": "aimer",
  "aimerait voyager": "aimer",
  "ait": "avoir",
  "ait abandonné": "abandonner",
  "ait accepté": "accepter",
  "ait compris": "comprendre",
  "ait demandé": "demander",
  "ait démontré": "démontrer",
  "ait dépassé": "dépasser",
  "ait éliminé": "éliminer",
  "ait fait": "faire",
  "ait atteint": "atteindre",
  "ait fini": "finir",
  "ait lu": "lire",
  "ait obtenu": "obtenir",
  "ait pris": "prendre",
  "ait proposée": "proposer",
  "ait proposé": "proposer",
  "ait remédié": "remédier",
  "ait reçu": "recevoir",
  "ait remporté": "remporter",
  "ait rencontrée": "rencontrer",
  "ait raté": "rater",
  "ait réussi": "réussir",
  "ait servi": "servir",
  "ait terminé": "terminer",
  "ayez formulé": "formuler",
  "ait gagné": "gagner",
  "ait travaillé": "travailler",
  "ait vu": "voir",
  "allaient": "aller",
  "allais": "aller",
  "allait": "aller",
  "allez": "aller",
  "Allez-y": "aller",
  "allions": "aller",
  "allons": "aller",
  "Allons": "aller",
  "appelle": "appeler",
  "appellent": "appeler",
  "appelles": "appeler",
  "appellerai": "appeler",
  "appellerait": "appeler",
  "appréciions": "apprécier",
  "apprenais": "apprendre",
  "apprends": "apprendre",
  "apprend": "apprendre",
  "apprendrait": "apprendre",
  "appuieras": "appuyer",
  "architectes": "nom",
  "éclate": "éclater",
  "ravage": "ravager",
  "crie": "crier",
  "gravit": "gravir",
  "franchit": "franchir",
  "reteniez": "retenir",
  "retentit": "retentir",
  "apparaît": "apparaître",
  "s'écrasent": "s'écraser",
  "fuit": "fuir",
  "saisit": "saisir",
  "frappe": "frapper",
  "se lève": "se lever",
  "se lèvera": "se lever",
  "raconte": "raconter",
  "libère": "libérer",
  "monte": "monter",
  "attaque": "attaquer",
  "emprunte": "emprunter",
  "brise": "briser",
  "emporte": "emporter",
  "glisse": "glisser",
  "examine": "examiner",
  "arrive": "arriver",
  "arrivions": "arriver",
  "arrivent": "arriver",
  "arrivera": "arriver",
  "arriveras": "arriver",
  "arriverez": "arriver",
  "arriverons": "arriver",
  "aurons atteint": "atteindre",
  "arriveront": "arriver",
  "aurons fini": "finir",
  "vont arriver": "arriver",
  "va arriver": "arriver",
  "atteindras": "atteindre",
  "arrivés": "arriver",
  "as": "avoir",
  "as-tu": "avoir",
  "Asseyez-vous": "s'asseoir",
  "assez de": "article",
  "assistions": "assister",
  "assumes": "assumer",
  "Attachez": "attacher",
  "atteigniez": "atteindre",
  "atteint": "atteindre",
  "attend": "attendre",
  "attendait": "attendre",
  "attendons": "attendre",
  "attends": "attendre",
  "a attendu": "attendre",
  "attendu": "attendre",
  "attendras": "attendre",
  "au": "article",
  "augmenteront": "augmenter",
  "auquel": "pronom relatif",
  "aura composé": "composer",
  "aura envoyé": "envoyer",
  "aura eu": "avoir",
  "aura perdu": "perdre",
  "aura trouvé": "trouver",
  "aura été": "être",
  "aurai fini": "finir",
  "aurai préparé": "préparer",
  "aurai terminé": "terminer",
  "auraient": "avoir",
  "auraient découvert": "découvrir",
  "auraient dû": "devoir",
  "auraient pu": "pouvoir",
  "auraient voulu": "vouloir",
  "auraient fait": "faire",
  "auraient vu": "voir",
  "aurais": "avoir",
  "aurais dû": "devoir",
  "aurais pu": "pouvoir",
  "aurais eu": "avoir",
  "aurais oublié": "oublier",
  "aurais réussi": "réussir",
  "aurais voulu": "vouloir",
  "aurait agi": "agir",
  "aurait aimé": "aimer",
  "aurait dû": "devoir",
  "aurait pu": "pouvoir",
  "aurait eu": "avoir",
  "aurait fait": "faire",
  "aurait occupé": "occuper",
  "aurait quitté": "quitter",
  "aurait vaincu": "vaincre",
  "vainc": "vaincre",
  "aurait été rédigé": "rédiger",
  "aurait remarqué": "remarquer",
  "ait remarqué": "remarquer",
  "a remarqué": "remarquer",
  "remarque": "remarquer",
  "remarquera": "remarquer",
  "remarquait": "remarquer",
  "aurait été": "être",
  "aurait": "avoir",
  "auras fini": "finir",
  "auras l'occasion": "avoir",
  "auras terminé": "terminer",
  "auras": "avoir",
  "aurez examiné": "examiner",
  "aurez fini": "finir",
  "aurez préparé": "préparer",
  "aurez rassemblé": "rassembler",
  "sembleraient": "sembler",
  "auriez dû": "devoir",
  "auriez peur": "avoir",
  "auriez pu": "pouvoir",
  "auriez": "avoir",
  "aurions": "avoir",
  "aurions acheté": "acheter",
  "aurions dû": "devoir",
  "aurions pu": "pouvoir",
  "aurons achevé": "achever",
  "aurons": "avoir",
  "auront oublié": "oublier",
  "auront réparé": "réparer",
  "aux": "article",
  "auxquelles": "pronom relatif",
  "auxquels": "pronom relatif",
  "avaient couru": "courir",
  "avaient cru": "croire",
  "avaient pris": "prendre",
  "avaient décidé": "décider",
  "avaient déjà étudié": "étudier",
  "avaient toujours cru": "croire",
  "avaient fini": "finir",
  "avaient fermé": "fermer",
  "avaient observé": "observer",
  "avaient le droit": "avoir",
  "avaient lu": "lire",
  "avaient oublié": "oublier",
  "avaient étudié": "étudier",
  "avaient été": "être",
  "aient été": "être",
  "ait validé": "valider",
  "avait fini": "finir",
  "avaient mangé": "manger",
  "avaient visité": "visiter",
  "avaient": "avoir",
  "avais dit": "dire",
  "avais pris": "prendre",
  "avais vu": "voir",
  "avais reçue": "recevoir",
  "aviez reçu": "recevoir",
  "avais": "avoir",
  "avait appelé": "appeler",
  "avait appris": "apprendre",
  "avait arrêté": "arrêter",
  "avait besoin de ce dont elle": "avoir besoin",
  "avait bu": "boire",
  "avait commencé": "commencer",
  "avait compris": "comprendre",
  "avait descendu": "descendre",
  "avait démarré": "démarrer",
  "démarré": "démarrer",
  "désirerait": "désirer",
  "avait dit": "dire",
  "avait déjà fermé": "fermer",
  "avait entendu": "entendre",
  "avait eu": "avoir",
  "avait fait": "faire",
  "avait fermé": "fermer",
  "avait gonflé": "gonfler",
  "avait perdu": "perdre",
  "avait pris": "prendre",
  "avait laissé": "laisser",
  "avait laissés": "laisser",
  "avait lu": "lire",
  "avait lus": "lire",
  "avait menti": "mentir",
  "avait quitté": "quitter",
  "avait reçues": "recevoir",
  "avait raté": "rater",
  "avait terminé": "terminer",
  "avait volé": "voler",
  "avait vu": "voir",
  "avait écrites": "écrire",
  "avait écrit": "écrire",
  "avait été accroché": "accrocher",
  "avait-on fermé": "fermer",
  "avait été": "être",
  "avait examiné": "examiner",
  "avait": "avoir",
  "avait-il compris": "comprendre",
  "avez expliqué": "expliquer",
  "avez fini": "finir",
  "avez rencontré": "rencontrer",
  "avez terminé": "terminer",
  "avez": "avoir",
  "aviez": "avoir",
  "avez-vous": "avoir",
  "N'avez-vous pas": "avoir",
  "N'avez-vous pas terminé": "avoir",
  "aviez demandé": "demander",
  "aviez expliqué": "expliquer",
  "aviez relu": "relire",
  "avions eu": "avoir",
  "avions défini": "définir",
  "avions étudié": "étudier",
  "avions organisé": "organiser",
  "avions retourné": "retourner",
  "avions signé": "signer",
  "avions préparé": "préparer",
  "avions vendu": "vendre",
  "avions-nous vu": "voir",
  "avions fermé": "fermer",
  "avions": "avoir",
  "avoir regardé": "regarder",
  "avoir lu": "lire",
  "avoir vendu": "vendre",
  "avons corrigé": "corriger",
  "avons classé": "classer",
  "avons eu": "avoir",
  "avons eu faim": "avoir",
  "avons pris": "prendre",
  "avons travaillé": "travailler",
  "avons vu": "voir",
  "avons": "avoir",
  "ayez acceptée": "accepter",
  "ayez accepté": "accepter",
  "ayez": "avoir",
  "ayez apprise": "apprendre",
  "ayez appris": "apprendre",
  "ayez faite": "faire",
  "ayez fini": "finir",
  "ayez inventé": "inventer",
  "ayez perdu": "perdre",
  "ayez lu": "lire",
  "ait prévenu": "prévenir",
  "ayez parlé": "parler",
  "ayez pu assister": "pouvoir",
  "ayez pu": "pouvoir",
  "ayez refusée": "refuser",
  "ayez reçue": "recevoir",
  "ayez reçu": "recevoir",
  "ayez terminés": "terminer",
  "ayez terminé": "terminer",
  "ayez trouvé": "trouver",
  "ayons compris": "comprendre",
  "ayons fait": "faire",
  "ayons manqué": "manquer",
  "ayons trouvée": "trouver",
  "ayons trouvé": "trouver",
  "ayons": "avoir",
  "ayant": "avoir",
  "beaucoup de": "article",
  "beaucoup": "adverbe",
  "a beaucoup": "adverbe",
  "a bien": "adverbe",
  "a bien réussi": "réussir",
  "a déjà lu": "lire",
  "as mal rédigé": "rédiger",
  "avons beaucoup travaillé": "travailler",
  "ont beaucoup voyagé": "voyager",
  "avez mal": "adverbe",
  "avons déjà": "adverbe",
  "ont toujours": "adverbe",
  "bois": "boire",
  "boit": "boire",
  "boive": "boire",
  "bu": "boire",
  "bougions": "bouger",
  "bout": "bouillir",
  "brillait": "briller",
  "buvais": "boire",
  "buvions": "boire",
  "buvons": "boire",
  "bâtissent": "bâtir",
  "ce dont": "pronom relatif",
  "ce à quoi": "pronom relatif",
  "Ce dont": "pronom relatif",
  "Ce que": "pronom relatif",
  "Ce qui": "pronom relatif",
  "changerais": "changer",
  "changeront": "changer",
  "chantait": "chanter",
  "chanté": "chanter",
  "cherchais": "chercher",
  "cherché": "chercher",
  "choisi": "choisir",
  "choisiras": "choisir",
  "choisirez": "choisir",
  "Choisis": "choisir",
  "commandait": "commander",
  "commence": "commencer",
  "commencera": "commencer",
  "commencerait": "commencer",
  "commençaient": "commencer",
  "commençons": "commencer",
  "comprenais": "comprendre",
  "comprenait": "comprendre",
  "comprendrez": "comprendre",
  "comprendrai": "comprendre",
  "comprends": "comprendre",
  "comprenne": "comprendre",
  "comprennent": "comprendre",
  "comprend": "comprendre",
  "comprendra": "comprendre",
  "comprendrait": "comprendre",
  "comprenions": "comprendre",
  "craignions": "craindre",
  "craignons": "craindre",
  "craignaient": "craindre",
  "craindraient": "craindre",
  "craindrons": "craindre",
  "craindre": "craindre",
  "craindrions": "craindre",
  "confiiez": "confier",
  "connaissez": "se connaître",
  "connais": "connaître",
  "connaît": "connaître",
  "connaisse": "connaître",
  "connaissais": "connaître",
  "connaissait": "connaître",
  "connaissiez": "connaître",
  "connaîtrais": "connaître",
  "connaîtrait": "connaître",
  "connaîtriez": "connaître",
  "a connu": "connaître",
  "ai connu": "connaître",
  "connus": "connaître",
  "Conserver": "conserver",
  "continuons": "continuer",
  "Continue": "continuer",
  "Observez": "observer",
  "construirais": "construire",
  "corrigées": "corriger",
  "courent": "courir",
  "courrai": "courir",
  "courrons": "courir",
  "criiez": "crier",
  "copiions": "copier",
  "croies": "croire",
  "croyiez": "croire",
  "croiriez": "croire",
  "croyez": "croire",
  "cru": "croire",
  "couvert": "couvrir",
  "cuisinerais": "cuisiner",
  "d'": "article",
  "d'oeufs et de": "article",
  "danse": "danser",
  "dansions": "danser",
  "de": "article",
  "de l'": "article",
  "de laquelle": "pronom relatif",
  "de partir": "partir",
  "descend": "descendre",
  "descende": "descendre",
  "descendait": "descendre",
  "défendront": "défendre",
  "demande": "demander",
  "demande pas": "demander",
  "demandais": "demander",
  "demanderais": "demander",
  "des": "article",
  "desquelles": "pronom relatif",
  "desquels": "pronom relatif",
  "dessines": "dessiner",
  "devaient": "devoir",
  "devenue": "devenir",
  "devez": "devoir",
  "deviendrons": "devenir",
  "devons": "devoir",
  "devrais faire": "devoir",
  "devrais": "devoir",
  "devrait": "devoir",
  "devrez": "devoir",
  "devriez": "devoir",
  "devrions": "devoir",
  "dire": "dire",
  "dirais": "dire",
  "dirait": "dire",
  "direz": "dire",
  "diriez": "dire",
  "dis": "dire",
  "disait": "dire",
  "dise": "dire",
  "dises": "dire",
  "disiez": "dire",
  "dit": "dire",
  "dites": "dire",
  "dites-la-nous": "dire",
  "doives": "devoir",
  "doive": "devoir",
  "dû": "devoir",
  "donne": "donner",
  "a donné": "donner",
  "donnait": "donner",
  "donnera": "donner",
  "donnerait": "donner",
  "donne-le-moi": "donner",
  "donne-m'en": "donner",
  "donne-moi": "donner",
  "donnent rendez-vous": "se donner rendez-vous",
  "donnerai": "donner",
  "donnons": "donner",
  "Dors": "dormir",
  "dorment": "dormir",
  "dont": "pronom relatif",
  "dormais": "dormir",
  "dormait": "dormir",
  "dormions": "dormir",
  "du": "article",
  "duquel": "pronom relatif",
  "déjà": "adverbe",
  "déjeunait": "déjeuner",
  "désirais": "désirer",
  "détruit": "détruire",
  "développeur": "nom",
  "dîner": "dîner",
  "Dépêchons-nous": "se dépêcher",
  "Détends-toi": "se détendre",
  "effaçait": "effacer",
  "emploieront": "employer",
  "en": "pronom",
  "Entendez": "entendre",
  "entendent": "entendre",
  "entends": "entendre",
  "entre": "entrer",
  "enverront": "envoyer",
  "envoie": "envoyer",
  "envoie-les-toi": "envoyer",
  "envoient": "envoyer",
  "envoies": "envoyer",
  "envoyer": "envoyer",
  "envoyez": "envoyer",
  "envoyons": "envoyer",
  "es allé / es allée": "aller",
  "es arrivé / es arrivée": "arriver",
  "es": "être",
  "essaies": "essayer",
  "essayé": "essayer",
  "essaierez": "essayer",
  "essuierons": "essuyer",
  "essuiera": "essuyer",
  "Est-ce qu'ils sont": "être",
  "Est-ce qu'il est": "aller",
  "Est-ce qu'il est allé": "aller",
  "Est-ce qu'il est allé à l'école ?": "aller",
  "Est-ce que": "comprendre",
  "est": "être",
  "est descendue": "descendre",
  "est entré": "entrer",
  "est entrée": "entrer",
  "est parti": "partir",
  "est retourné": "retourner",
  "est sortie": "sortir",
  "Est-ce": "être",
  "eu": "avoir",
  "eûmes": "avoir",
  "examinerez": "examiner",
  "examiné": "examiner",
  "Excusez-moi": "s'excuser",
  "eût terminé": "terminer",
  "Fais attention": "faire",
  "fais": "faire",
  "faisais": "faire",
  "faisait": "faire",
  "faisaient": "faire",
  "faisiez": "faire",
  "faisions": "faire",
  "faisons pas": "faire",
  "Ne faisons pas": "faire",
  "fait": "faire",
  "faites": "faire",
  "fasse": "faire",
  "fasses": "faire",
  "fassent": "faire",
  "fassiez": "faire",
  "fassions": "faire",
  "faisons": "faire",
  "faut": "falloir",
  "faudrait": "falloir",
  "fera": "faire",
  "feront": "faire",
  "font": "faire",
  "ferais": "faire",
  "feraient": "faire",
  "ferait": "faire",
  "feriez": "faire",
  "ferions": "faire",
  "Fermez": "fermer",
  "fini": "finir",
  "finisse": "finir",
  "finit": "finir",
  "finir": "finir",
  "finirai": "finir",
  "finirait": "finir",
  "finiras": "finir",
  "finira": "finir",
  "finirais": "finir",
  "finis": "finir",
  "avait arrosé": "arroser",
  "finissent": "finir",
  "finissiez": "finir",
  "finissais": "finir",
  "finisses": "finir",
  "finiriez": "finir",
  "finissez": "finir",
  "finissons": "finir",
  "finirez": "finir",
  "finirions": "finir",
  "finirons": "finir",
  "finissions": "finir",
  "Fournissez": "fournir",
  "fourniront": "fournir",
  "fondu": "fondre",
  "français": "nom",
  "grandis": "grandir",
  "grandisse": "grandir",
  "choisisses": "choisir",
  "choisisse": "choisir",
  "choisit": "choisir",
  "choisis": "choisir",
  "choisir": "choisir",
  "choisirais": "choisir",
  "parlions": "parler",
  "réussissiez": "réussir",
  "réfléchissions": "réfléchir",
  "gèle": "geler",
  "habitait": "habiter",
  "habite": "habiter",
  "habitiez": "habiter",
  "habitions": "habiter",
  "honnêtement": "adverbe",
  "Il faut": "falloir",
  "Invite": "inviter",
  "inviterons": "inviter",
  "invité": "inviter",
  "ira": "aller",
  "irait": "aller",
  "iriez": "aller",
  "irions": "aller",
  "irons": "aller",
  "japonais": "nom",
  "jette": "jeter",
  "jettent": "jeter",
  "jettes": "jeter",
  "jetterez": "jeter",
  "joint": "joindre",
  "lisaient": "lire",
  "emmenait": "emmener",
  "mangiez": "manger",
  "nettoyais": "nettoyer",
  "mangeait": "manger",
  "commençais": "commencer",
  "rangeait": "ranger",
  "commencions": "commencer",
  "commençait": "commencer",
  "annonçaient": "annoncer",
  "annonçait": "annoncer",
  "lancions": "lancer",
  "rangeiez": "ranger",
  "partageait": "partager",
  "partagions": "partager",
  "commenciez": "commencer",
  "annonçent": "annoncer",
  "joue": "jouer",
  "jouait": "jouer",
  "jouions": "jouer",
  "l'": "...",
  "L'": "...",
  "l'appelle": "appeler",
  "la France": "nom",
  "la leçon": "nom",
  "la lui": "pronom",
  "la": "...",
  "La": "...",
  "la-lui": "pronom",
  "la-moi": "pronom",
  "laquelle": "pronom relatif",
  "le lui": "pronom",
  "le mandarin": "nom",
  "le signer": "signer",
  "le sache": "savoir",
  "le sait": "savoir",
  "le saura": "savoir",
  "le savait": "savoir",
  "le suédois": "nom",
  "le": "...",
  "Le": "...",
  "les": "...",
  "Les": "...",
  "les accompagner": "...",
  "les écoutez": "...",
  "les leur": "pronom",
  "les y": "pronom",
  "le-lui": "pronom",
  "le-moi": "pronom",
  "les-leur": "pronom",
  "lesquelles": "pronom relatif",
  "lesquels": "pronom relatif",
  "leur en": "pronom",
  "leur": "pronom",
  "Lisez": "lire",
  "lirais": "lire",
  "lira": "lire",
  "lirait": "lire",
  "lit": "lire",
  "lisait": "lire",
  "lisais": "lire",
  "lire": "lire",
  "lise": "lire",
  "lisent": "lire",
  "livrerons": "livrer",
  "lu": "lire",
  "lues": "lire",
  "lui en dis": "dire",
  "lui": "pronom",
  "Lève-toi": "se lever",
  "m'": "pronom",
  "m'appellerais": "appeler",
  "Mange": "manger",
  "mange": "manger",
  "mangeons": "manger",
  "mangeras": "manger",
  "Manges": "manger",
  "manges": "manger",
  "mangions": "manger",
  "manque": "manquer",
  "manquent": "manquer",
  "marchait": "marcher",
  "marché": "marcher",
  "parlé": "parler",
  "a parlé": "parler",
  "dormi": "dormir",
  "ont dormi": "dormir",
  "pleuré": "pleurer",
  "a pleuré": "pleurer",
  "couru": "courir",
  "a dormi": "dormir",
  "mangé": "manger",
  "travaillé": "travailler",
  "ont couru": "courir",
  "me contacteriez": "contacter",
  "me la dis": "dire",
  "me la donne": "donner",
  "me la": "pronom",
  "me lavais": "se laver",
  "me le prête": "prêter",
  "me le": "pronom",
  "me les envoyez": "envoyer",
  "me lève": "se lever",
  "me reposer": "se reposer",
  "me": "pronom",
  "met": "mettre",
  "mettes": "mettre",
  "mettras": "mettre",
  "mettrais": "mettre",
  "mettre": "mettre",
  "mis": "mettre",
  "montre-les-lui": "montrer",
  "montrerai": "montrer",
  "morte": "mourir",
  "mourra": "mourir",
  "mourrez": "mourir",
  "mécaniciens": "nom",
  "neige": "neiger",
  "né": "naître",
  "n'ai": "avoir",
  "n'as pas": "négation",
  "n'avons pas": "négation",
  "n'ait abandonné": "abandonner",
  "n'ait pas abandonné": "abandonner",
  "n'aura pas fini": "finir",
  "n'aurais": "avoir",
  "n'aurait": "avoir",
  "n'aurait invité personne": "inviter",
  "n'aurait jamais vu": "voir",
  "n'aurez jamais eu": "avoir",
  "n'avaient rien dit": "dire",
  "n'avaient pas encore pris": "prendre",
  "avaient pas encore pris": "prendre",
  "n'avais invité personne": "inviter",
  "n'avait pas mangé": "manger",
  "n'avions jamais vu": "voir",
  "n'en": "article",
  "n'est": "être",
  "n'est pas": "négation",
  "ne sont pas": "négation",
  "n'ont": "avoir",
  "n'ont pas": "négation",
  "n'a pas": "négation",
  "n'avez pas": "négation",
  "n'avait pas lu": "lire",
  "n'avait jamais reçu": "recevoir",
  "n'avait pas encore examiné": "examiner",
  "n'y va pas": "aller",
  "n'y": "pronom",
  "Nage": "nager",
  "nageons": "nager",
  "nagerai": "nager",
  "ne change": "changer",
  "ne comprendrais pas": "comprendre",
  "ne dirais rien": "dire",
  "ne lui fassiez des reproches": "faire",
  "ne mange pas de bonbons": "manger",
  "ne nous battons pas": "se battre",
  "ne parle pas": "parler",
  "ne parlez pas fort": "parler",
  "ne pas exposer": "exposer",
  "ne pas laisser": "laisser",
  "ne stationnez pas": "stationner",
  "ne rencontreriez": "rencontrer",
  "ne réveille": "réveiller",
  "ne s'est": "se lever",
  "ne se fâche": "se fâcher",
  "ne se serait pas trompée": "se tromper",
  "ne serais": "être",
  "ne soit trop tard": "être",
  "ne soit": "être",
  "ne soyez trop fatigués": "être",
  "ne dise": "dire",
  "ne fassiez": "faire",
  "ne mettions": "mettre",
  "ne s'en aille": "s'en aller",
  "ne voies": "voir",
  "nettoierai": "nettoyer",
  "nettoie": "nettoyer",
  "nettoient": "nettoyer",
  "nettoiera": "nettoyer",
  "nettoies": "nettoyer",
  "nettoyé": "nettoyer",
  "nourrissent": "nourrir",
  "nous dépêchions": "se dépêcher",
  "nous couchions": "se coucher",
  "nous inquiétons": "s'inquiéter",
  "s'inquiète": "s'inquiéter",
  "nous les montrez": "montrer",
  "nous les": "pronom",
  "nous nous étions dépêchés": "se dépêcher",
  "nous nous étions rendu compte": "se rendre compte",
  "nous reposerions": "se reposer",
  "se brossait": "se brosser",
  "se rasait": "se raser",
  "nous retrouverons": "se retrouver",
  "nous souvenons": "se souvenir",
  "nous voyions": "voir",
  "étions déjà partis": "partir",
  "nous": "pronom",
  "nés": "naître",
  "obligiez": "obliger",
  "offert": "offrir",
  "ont attendu": "attendre",
  "ont vendu": "vendre",
  "ont visité": "visiter",
  "court": "courir",
  "découvre": "découvrir",
  "découvre pas": "découvrir",
  "découvrira": "découvrir",
  "découvrait": "découvrir",
  "repère": "repérer",
  "ont éteint": "éteindre",
  "ont pu": "pouvoir",
  "ont": "avoir",
  "oubliions": "oublier",
  "oublié": "oublier",
  "ouvert": "ouvrir",
  "où": "pronom relatif",
  "paie": "payer",
  "paierai": "payer",
  "paierons": "payer",
  "parcoure": "parcourir",
  "parlait": "parler",
  "parle": "parler",
  "parle-lui": "parler",
  "parlons": "se parler",
  "partons": "partir",
  "part": "partir",
  "partent": "partir",
  "parte": "partir",
  "partes": "partir",
  "partie": "partir",
  "préparé": "préparer",
  "partions": "partir",
  "partir": "partir",
  "partiras": "partir",
  "pars": "partir",
  "passais": "passer",
  "passait": "passer",
  "passent": "passer",
  "passer": "passer",
  "passerez": "passer",
  "passions": "passer",
  "payons": "payer",
  "payé": "payer",
  "peint": "peindre",
  "pensait": "penser",
  "penses": "penser",
  "perd": "perdre",
  "perde": "perdre",
  "perdais": "perdre",
  "perds": "perdre",
  "perdez": "perdre",
  "perdu": "perdre",
  "Permettez-moi": "permettre",
  "personne": "pronom indéfini",
  "peu de": "article",
  "peuvent": "pouvoir",
  "peut": "pouvoir",
  "peux": "pouvoir",
  "plaît": "plaire",
  "plais": "plaire",
  "plaisait": "plaire",
  "plairait": "plaire",
  "plaisent": "plaire",
  "plaçais": "placer",
  "plaçons": "placer",
  "pleut": "pleuvoir",
  "pleuvra": "pleuvoir",
  "pleuvrait": "pleuvoir",
  "Pourriez": "pouvoir",
  "pourra": "pouvoir",
  "pourrai": "pouvoir",
  "pourraient": "pouvoir",
  "pourrez": "pouvoir",
  "pourrais": "pouvoir",
  "pourras": "pouvoir",
  "pourrait": "pouvoir",
  "pourriez": "pouvoir",
  "pourrions accepter": "pouvoir",
  "pourrions": "pouvoir",
  "pourront": "pouvoir",
  "poursuive": "poursuivre",
  "poursuives": "poursuivre",
  "poursuivra": "poursuivre",
  "poursuivait": "poursuivre",
  "pouvais": "pouvoir",
  "pouvait": "pouvoir",
  "pouvions": "pouvoir",
  "pouvons": "pouvoir",
  "pouviez": "pouvoir",
  "Prendriez": "prendre",
  "prenait": "prendre",
  "prend": "prendre",
  "prendrais": "prendre",
  "prendrait": "prendre",
  "prendraient": "prendre",
  "prendrions": "prendre",
  "prendrons": "prendre",
  "Prends": "prendre",
  "prends": "prendre",
  "prenne": "prendre",
  "prennes": "prendre",
  "preniez": "prendre",
  "prenions": "prendre",
  "prenons": "prendre",
  "presse": "presser",
  "pris": "prendre",
  "prise": "prendre",
  "prises": "prendre",
  "Prépare-toi": "se préparer",
  "profitiez": "profiter",
  "promets-toi": "promettre",
  "préparions": "préparer",
  "présent": "temps verbal",
  "prête-la-nous": "prêter",
  "puisse": "pouvoir",
  "puissent": "pouvoir",
  "puisses": "pouvoir",
  "puissiez": "pouvoir",
  "puissions": "pouvoir",
  "qu'elles aient complété": "compléter",
  "aient complété": "compléter",
  "aient terminé": "terminer",
  "qu'il ait échoué": "échouer",
  "ait échoué": "échouer",
  "que": "pronom relatif",
  "que tu sois": "être",
  "qu'elle soit": "être",
  "qu'ils fassent": "faire",
  "qu'elle poursuive": "poursuivre",
  "qu'il dise": "dire",
  "que vous soyez": "être",
  "qui jouent dans le parc": "jouer",
  "qui": "pronom relatif",
  "quitte": "quitter",
  "rangé": "ranger",
  "rangeras": "ranger",
  "rapidamente": "adverbe",
  "rappelle": "rappeler",
  "rappellent": "rappeler",
  "rappelles": "rappeler",
  "rappelons": "rappeler",
  "recevait": "recevoir",
  "recommandés": "recommander",
  "rembourserai": "rembourser",
  "reconnaissions": "reconnaître",
  "Regarde": "regarder",
  "redoublez": "redoubler",
  "regardaient": "regarder",
  "regarde": "regarder",
  "regardent": "regarder",
  "regardons": "regarder",
  "regardé": "regarder",
  "rejette": "rejeter",
  "rejettent": "rejeter",
  "rejettes": "rejeter",
  "rejetterons": "rejeter",
  "rejoint": "rejoindre",
  "Remplissons": "remplir",
  "rempli": "remplir",
  "rencontre": "rencontrer",
  "rencontrez": "rencontrer",
  "rencontrerez": "rencontrer",
  "rencontreriez": "rencontrer",
  "rencontriez": "rencontrer",
  "rencontrâtes": "rencontrer",
  "rencontrerons": "rencontrer",
  "rendait visite à": "rendre visite à",
  "rendu": "rendre",
  "Rentre": "rentrer",
  "rentre": "rentrer",
  "rentrent": "rentrer",
  "renouvelleront": "renouveler",
  "reprennent": "reprendre",
  "retrouvais": "retrouver",
  "retrouvent": "se retrouver",
  "se connait": "se connaître",
  "se connaissent": "se connaître (action mutuelle)",
  "se disent": "se dire (action mutuelle)",
  "se saluent": "se saluer (action mutuelle)",
  "se retrouvent": "se retrouver (action mutuelle)",
  "se téléphonent": "se téléphoner (action mutuelle)",
  "reviennes": "revenir",
  "reçois": "recevoir",
  "reçoit": "recevoir",
  "réalise": "réaliser",
  "réfléchissaient": "réfléchir",
  "répondez": "répondre",
  "réponds": "répondre",
  "Réponds": "répondre",
  "répondes": "répondre",
  "répondre": "répondre",
  "répondras": "répondre",
  "répondrais": "répondre",
  "répondrai": "répondre",
  "résolu": "résoudre",
  "résoudra": "résoudre",
  "résoudrait": "résoudre",
  "résout": "résoudre",
  "résolve": "résoudre",
  "résolvions": "résoudre",
  "résolvons": "résoudre",
  "résoudrons": "résoudre",
  "résoudre": "résoudre",
  "résoudrions": "résoudre",
  "résolvaient": "résoudre",
  "résoudraient": "résoudre",
  "réussi": "réussir",
  "réussira": "réussir",
  "réussirais": "réussir",
  "réussisse": "réussir",
  "réussissait": "réussir",
  "réussit": "réussir",
  "réveille": "réveiller",
  "réveille pas": "réveiller",
  "réveillera": "réveiller",
  "réveillait": "réveiller",
  "Réveillons-nous": "se réveiller",
  "s'agit": "s'agir",
  "s'agit de": "s'agir",
  "s'en aperçoive": "s'apercevoir",
  "s'en aperçoit": "s'apercevoir",
  "s'en aperçoivent": "s'apercevoir",
  "s'en aperçoivent pas": "s'apercevoir",
  "s'en aperçoivent déjà": "s'apercevoir",
  "s'en est aperçu": "s'apercevoir",
  "s'en apercevait": "s'apercevoir",
  "s'en apercevoir": "s'apercevoir",
  "s'en sont aperçus": "s'apercevoir",
  "s'est assis": "s'asseoir",
  "s'est cassé": "se casser",
  "s'est réveillée": "se réveiller",
  "se sont blessés": "se blesser",
  "s'est peigné": "se peigner",
  "se sont retrouvés": "se retrouver",
  "s'est dépêchée": "se dépêcher",
  "s'est lavée": "se laver",
  "s'est éteinte": "s'éteindre",
  "s'habillait": "s'habiller",
  "s'étaient habillées": "s'habiller",
  "s'étaient regardés": "se regarder",
  "s'étaient rencontrés": "se rencontrer",
  "s'était levé": "se lever",
  "s'était levée": "se lever",
  "s'était passé": "se passer",
  "s'était souvenue": "se souvenir",
  "s'était tordu": "se tordre",
  "s'était ouverte": "s'ouvrir",
  "s'était": "se souvenir",
  "Sache": "savoir",
  "sache": "savoir",
  "sait": "savoir",
  "veuille": "vouloir",
  "veut": "vouloir",
  "voulait": "vouloir",
  "veuillent": "vouloir",
  "saches": "savoir",
  "sachiez": "savoir",
  "sachions": "savoir",
  "saura": "savoir",
  "savait": "savoir",
  "Saisissons": "saisir",
  "saisie": "saisir",
  "saisirez": "saisir",
  "saisira": "saisir",
  "saisir": "saisir",
  "saisisse": "saisir",
  "saisissait": "saisir",
  "saisis": "saisir",
  "sauras": "savoir",
  "saurait": "savoir",
  "saurez": "savoir",
  "sauriez": "savoir",
  "saurions": "savoir",
  "saurons": "savoir",
  "savez": "savoir",
  "savais": "savoir",
  "saviez": "savoir",
  "se sent": "se sentir",
  "se sera perdu": "se perdre",
  "se sera réveillée": "se réveiller",
  "se soient battus": "se battre",
  "se soient reposées": "se reposer",
  "se soit levé": "se lever",
  "se soit mise": "se mettre",
  "se soit trompée": "se tromper",
  "se sont amusées": "s'amuser",
  "se sont dépêchés": "se dépêcher",
  "se souvenaient": "se souvenir",
  "regretteras": "regretter",
  "se terminent": "se terminer",
  "sentait": "sentir",
  "sera arrivé": "arriver",
  "sera arrivée": "arriver",
  "sera montée": "monter",
  "sera": "être",
  "serai": "être",
  "seraient venus": "venir",
  "seraient": "être",
  "serais allé": "aller",
  "serais parti": "partir",
  "serais": "être",
  "serait annulé": "être",
  "serait": "être",
  "seras": "être",
  "serez": "être",
  "seriez": "être",
  "serions": "être",
  "serions allés": "aller",
  "seront parties": "partir",
  "seront": "être",
  "Sois": "être",
  "sois partie": "partir",
  "sois": "être",
  "soit allé": "aller",
  "soit arrivée": "arriver",
  "soit partie": "partir",
  "soit revenue": "revenir",
  "soit venue": "venir",
  "soit": "être",
  "sommes allés": "aller",
  "sommes allés / sommes allées": "aller",
  "sommes restés": "rester",
  "resterions": "rester",
  "sommes": "être",
  "serons": "être",
  "Sont-ils": "être",
  "sont": "être",
  "sont-ils": "être",
  "sont-ils rentrés": "être",
  "Sont-ils rentrés": "rentrer",
  "sont arrivés": "arriver",
  "sont descendues": "descendre",
  "sont descendus": "descendre",
  "sont devenus": "devenir",
  "sont passées": "passer",
  "Sortez": "sortir",
  "sort": "sortir",
  "sorte": "sortir",
  "sortait": "sortir",
  "sortirait": "sortir",
  "sortons": "sortir",
  "sorties": "sortir",
  "soufflait": "souffler",
  "souffert": "souffrir",
  "souhaitais": "souhaiter",
  "souhaiterions": "souhaiter",
  "souhaiteriez": "souhaiter",
  "soumises": "soumettre",
  "soyez partis": "partir",
  "soyez venu(s)": "venir",
  "soyez venus": "venir",
  "Soyons": "être",
  "soyez": "être",
  "soyons arrivés": "arriver",
  "soyons d'accord": "être",
  "soyons partis": "partir",
  "soyons": "être",
  "Suivez": "suivre",
  "suive": "suivre",
  "suivre": "suivre",
  "suit": "suivre",
  "suivra": "suivre",
  "suffit": "suffire",
  "suis sorti / suis sortie": "sortir",
  "suis": "être",
  "suiviez": "suivre",
  "suivions": "suivre",
  "suivons": "suivre",
  "suivrons": "suivre",
  "suivrions": "suivre",
  "suivraient": "suivre",
  "suivaient": "suivre",
  "sur lequel": "pronom relatif",
  "surmonterons": "surmonter",
  "symphonie": "nom",
  "t'": "pronom",
  "t'assois": "s'asseoir",
  "t'étais blessé": "se blesser",
  "avait choisi": "choisir",
  "avait cueillies": "cueillir",
  "avions attendu": "attendre",
  "te couche": "se coucher",
  "te couches": "se coucher",
  "te dépêche": "se dépêcher",
  "te la": "pronom",
  "te": "pronom",
  "tenais": "tenir",
  "teniez": "tenir",
  "terminer": "terminer",
  "terminerai": "terminer",
  "terminerez": "terminer",
  "termines": "terminer",
  "terminés": "terminer",
  "tiendra": "tenir",
  "tiendras": "tenir",
  "tiens": "tenir",
  "tiennes": "tenir",
  "tenir": "tenir",
  "touche": "toucher",
  "toujours": "adverbe",
  "traiterons": "traiter",
  "travaillait": "travailler",
  "travaille": "travailler",
  "travaillerai": "travailler",
  "travaillez": "travailler",
  "trop de": "article",
  "trompez": "se tromper",
  "trompiez": "se tromper",
  "tromperez": "se tromper",
  "trouve": "trouver",
  "trouve pas": "trouver",
  "trouvais": "trouver",
  "trouverais": "trouver",
  "trouveras": "trouver",
  "trouviez": "trouver",
  "téléphone-nous": "téléphoner",
  "téléphones": "téléphoner",
  "Un": "article",
  "un": "article",
  "un film": "nom",
  "une avocate": "nom",
  "une infirmière": "nom",
  "une": "article",
  "utiliserez": "utiliser",
  "Va": "aller",
  "va": "aller",
  "va marcher": "marcher",
  "va partir": "partir",
  "va pleuvoir": "pleuvoir",
  "va tomber": "tomber",
  "Vas": "aller",
  "Vas-y": "aller",
  "vais": "aller",
  "vaut": "valoir",
  "Veuillez": "vouloir",
  "venais": "venir",
  "vendons": "vendre",
  "vendrons": "vendre",
  "venez": "venir",
  "veniez": "venir",
  "venions": "venir",
  "verrai": "voir",
  "verrais": "voir",
  "verrait": "voir",
  "voit": "voir",
  "voyait": "voir",
  "voyais": "voir",
  "irons jamais": "aller",
  "verrai personne": "voir",
  "verras": "voir",
  "atteindrez": "atteindre",
  "verrez": "voir",
  "verriez": "voir",
  "voyez": "voir",
  "voyiez": "voir",
  "verrons": "rencontrer",
  "veux": "vouloir",
  "viendrai": "venir",
  "viendrait": "venir",
  "viendraient": "venir",
  "viendras": "venir",
  "vienne": "venir",
  "viennes": "venir",
  "vient": "venir",
  "viens": "venir",
  "venir": "venir",
  "visiterais": "visiter",
  "visité": "visiter",
  "vivait": "vivre",
  "vivra": "vivre",
  "vivrait": "vivre",
  "vive": "vivre",
  "vivions": "vivre",
  "vit": "vivre",
  "vivons": "vivre",
  "vivrons": "vivre",
  "vivre": "vivre",
  "vivrions": "vivre",
  "vivraient": "vivre",
  "vivaient": "vivre",
  "voie": "voir",
  "vois": "voir",
  "vont": "aller",
  "voudra": "vouloir",
  "voudrais": "vouloir",
  "voudrait": "vouloir",
  "voulais": "vouloir",
  "vouliez": "vouloir",
  "voulu": "vouloir",
  "vous couchiez": "se coucher",
  "vous les": "pronom",
  "vous levez": "se lever",
  "vous plaignez": "se plaindre",
  "se plaignent": "se plaindre",
  "se plaignent pas": "se plaindre",
  "se plaindront": "se plaindre",
  "se plaignaient": "se plaindre",
  "se sont plaints": "se plaindre",
  "vous préparez": "se préparer",
  "vous soyez souvenus": "se souvenir",
  "vous êtes habillés/habillées": "s'habiller",
  "voyageons": "voyager",
  "voyagerais": "voyager",
  "vu": "voir",
  "vérifi era": "vérifier",
  "vérifierais": "vérifier",
  "vérifiions": "vérifier",
  "vérifiiez": "vérifier",
  "y a": "y avoir",
  "y en": "pronom",
  "y va": "aller",
  "y": "pronom",
  "Écoute": "écouter",
  "écoutais": "écouter",
  "écouterais": "écouter",
  "Écoutons": "écouter",
  "écoutiez": "écouter",
  "écris": "écrire",
  "écrit": "écrire",
  "écris-leur": "écrire",
  "écrivent": "s'écrire",
  "épelle": "épeler",
  "épellent": "épeler",
  "épelles": "épeler",
  "épellera": "épeler",
  "établi": "établir",
  "établirons": "établir",
  "étaient rentrées": "rentrer",
  "étaient parties": "partir",
  "étaient partis": "partir",
  "étaient": "être",
  "étaient-ils rentrés": "rentrer",
  "étais venu": "venir",
  "avais-je compris": "comprendre",
  "avais appelé": "appeler",
  "étais": "être",
  "était-elle arrivée": "arriver",
  "était-elle sortie": "sortir",
  "était allée": "aller",
  "était arrivé": "arriver",
  "était arrivée": "arriver",
  "étaient arrivés": "arriver",
  "était devenu": "devenir",
  "était entré": "entrer",
  "était retournée": "retourner",
  "était parti": "partir",
  "était partie": "partir",
  "était sortie": "sortir",
  "était venue": "venir",
  "était venu": "venir",
  "était": "être",
  "être": "être",
  "étiez": "être",
  "étions arrivés": "arriver",
  "étions": "être",
  "étudie": "étudier",
  "étudierait": "étudier",
  "étudiez": "étudier",
  "étudions": "étudier",
  "étudiions": "étudier",
  "êtes trompés": "se tromper",
  "êtes venu": "venir",
  "êtes": "être",
  "être allés": "aller",
  "soient allés": "aller",
  "être parti": "partir",
  "mal": "adverbe",
  "Avez-vous": "avoir",
  "Avez-vous terminé": "terminer",
  "ne partirai pas": "partir",
  "Auriez-vous": "avoir",
  "soient": "être",
  "soient partis": "partir",
  "Continuons": "continuer",
  "Ayons": "avoir",
  "Ayez": "avoir",
  "N'y va pas": "aller",
  "Ne les écoutez pas": "écouter",
  "N'attendons pas": "attendre",
  "Regarde-la": "regarder",
  "Prends-les": "prendre",
  "Mange-les": "manger",
  "Écoute-le": "écouter",
  "Lisez-la": "lire",
  "Parle-lui": "parler",
  "Écris-leur": "écrire",
  "Donne-moi": "donner",
  "Téléphone-nous": "téléphoner",
  "Répondez-lui": "répondre",
  "Ne la regarde pas": "regarder",
  "Ne lui parlez pas": "parler",
  "Ne te lève pas": "se lever",
  "Ne les mangez pas": "manger",
  "Ne l'appelle pas": "appeler",
  "Ne parle pas": "parler",
  "N'y": "pronom",
  "N'en": "article",
  "Ne parlez pas fort": "parler",
  "Ne mange pas de bonbons": "manger",
  "Ne nous battons pas": "se battre",
  "Ne stationnez pas": "stationner",
  "Ne cours pas": "courir",
  "Laver": "laver",
  "Ne pas exposer": "exposer",
  "Ne pas laisser": "laisser",
  "Donne-m'en": "donner",
  "polonais": "nom",
  "souvenons": "se souvenir",
  "pratique": "pratiquer",
  "préparez": "se préparer",
  "Le mandarin": "nom",
  "avait mangé": "manger",
  "avaient dépensé": "dépenser",
  "t'étais arrêté": "s'arrêter",
  "avait détruit": "détruire",
  "avait étudié": "étudier",
  "avait révisé": "réviser",
  "avions oublié": "oublier",
  "avais prêté": "prêter",
  "avait envoyé": "envoyer",
  "avait changé": "changer",
  "avait oublié": "oublier",
  "est venu": "venir",
  "est allée": "aller",
  "serait parti": "partir",
  "serait venu": "venir",
  "serait allée": "aller",
  "serait arrivée": "arriver",
  "seraient partis": "partir",
  "aurait compris": "comprendre",
  "aurait mangé": "manger",
  "aurait perdu": "perdre",
  "aurait commencé": "commencer",
  "aurait détruit": "détruire",
  "aurait étudié": "étudier",
  "aurait raté": "rater",
  "aurait fini": "finir",
  "aurait fallu": "falloir",
  "aurait envoyé": "envoyer",
  "aurait changé": "changer",
  "aurait oublié": "oublier",
  "auraient dépensé": "dépenser",
  "aurait réussi": "réussir",
  "auraient réussi": "réussir",
  "aurions oublié": "oublier",
  "aurais prêté": "prêter",
  "avait changer": "changer",
  "avait commencer": "commencer",
  "avait commencée": "commencer",
  "était commencé": "commencer",
  "avait eu oublié": "oublier",
  "avait oubliée": "oublier",
  "était perdu": "perdre",
  "avaient parti": "partir",
  "seront partis": "partir",
  "aura commencé": "commencer",
  "aura changé": "changer",
  "aura oublié": "oublier",
  "partait": "partir",
  "partirait": "partir",
  "partaient": "partir",
  "perdait": "perdre",
  "venait": "venir",
  "dépensaient": "dépenser",
  "t'arrêtais": "s'arrêter",
  "détruisait": "détruire",
  "étudiait": "étudier",
  "ratait": "rater",
  "rataient": "rater",
  "ratent": "rater",
  "ratent pas": "rater",
  "rateront": "rater",
  "finissait": "finir",
  "quittait": "quitter",
  "prêtais": "prêter",
  "changeait": "changer",
  "oubliait": "oublier",
  "ont dépensé": "dépenser",
  "a commencé": "commencer",
  "t'es arrêté": "s'arrêter",
  "a détruit": "détruire",
  "a étudié": "étudier",
  "sont partis": "partir",
  "avons oublié": "oublier",
  "a quitté": "quitter",
  "as prêté": "prêter",
  "a changé": "changer",
  "terminait": "terminer",
  "aurait terminé": "terminer",
  "avait oublier": "oublier",
  "te serais arrêté": "s'arrêter",
  "Il a réussi son examen parce qu'il avait beaucoup révisé.": "réviser",
  "Il a réussi son examen parce qu'il a beaucoup révisé.": "réviser",
  "Il a réussi son examen parce qu'il révisait beaucoup.": "réviser",
  "Il a réussi son examen parce qu'il aurait beaucoup révisé.": "réviser",
  "Quand j'ai ouvert la lettre, j'ai compris qu'il avait déjà envoyé sa réponse.": "envoyer",
  "Quand j'ai ouvert la lettre, j'ai compris qu'il a déjà envoyé sa réponse.": "envoyer",
  "Quand j'ai ouvert la lettre, j'ai compris qu'il envoyait déjà sa réponse.": "envoyer",
  "Quand j'ai ouvert la lettre, j'ai compris qu'il aurait déjà envoyé sa réponse.": "envoyer",
  "vivront": "vivre",
  "vont vivre": "vivre",
  "démissionnerai": "démissionner",
  "portera": "porter",
  "va porter": "porter",
  "décollera": "décoller",
  "calera": "caler",
  "paiera": "payer",
  "va payer": "payer",
  "entrera": "entrer",
  "va entrer": "entrer",
  "atteindra": "atteindre",
  "adopterait": "adopter",
  "va atteindre": "atteindre",
  "brûlera": "brûler",
  "va mordre": "mordre",
  "mordra": "mordre",
  "vont augmenter": "augmenter",
  "vais quitter": "quitter",
  "quitterai": "quitter",
  "va frapper": "frapper",
  "frappera": "frapper",
  "débordera": "déborder",
  "raterons": "rater",
  "enverras": "envoyer",
  "obtiendra": "obtenir",
  "obtient": "obtenir",
  "obtiennes": "obtenir",
  "obtienne": "obtenir",
  "s'effondrera": "s'effondrer",
  "va s'effondrer": "s'effondrer",
  "atterrira": "atterrir",
  "entendrait": "entendre",
  "réussisses": "réussir",
  "aidiez": "aider",
  "terminerait": "terminer",
  "décidera": "décider",
  "fermerait": "fermer",
  "lises": "lire",
  "partirais": "partir",
  "pleuve": "pleuvoir",
  "aies": "avoir",
  "viendrais": "venir",
};

export type AnswerHintKey = keyof typeof answerHints;
