/**
 * Prebuild script: fetches the allow-list from a GitHub Gist URL and writes
 * it to src/lib/allow-list-data.ts (gitignored).
 *
 * If ALLOW_LIST_GIST_URL is not set, writes an empty set.
 * Run: npx tsx scripts/fetch-allowlist.ts
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";

const OUTPUT = join(
  import.meta.dirname,
  "..",
  "src",
  "lib",
  "allow-list-data.ts",
);

async function main() {
  const url = process.env.ALLOW_LIST_GIST_URL;
  let ids: string[] = [];

  if (url) {
    console.log(`Fetching allow-list from ${url}`);
    const res = await fetch(url);
    if (!res.ok) {
      throw new Error(
        `Failed to fetch allow-list: ${res.status} ${res.statusText}`,
      );
    }
    const text = await res.text();
    ids = text
      .split("\n")
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith("#"));
    console.log(`Loaded ${ids.length} allowed user(s)`);
  } else {
    console.log("ALLOW_LIST_GIST_URL not set — writing empty allow-list");
  }

  const content = `// Auto-generated by scripts/fetch-allowlist.ts — do not edit
export const ALLOW_LIST: ReadonlySet<string> = new Set([
${ids.map((id) => `  ${JSON.stringify(id)},`).join("\n")}
]);
`;

  writeFileSync(OUTPUT, content);
  console.log(`Wrote ${OUTPUT}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
