import { mangleUserId } from "./mangle";
import { env } from "~/config/env";

let devAllowedId: string | undefined;
let allowSet: Set<string> | undefined;

/**
 * Load the allow-list generated at build time (if available).
 * The file is gitignored and generated by the prebuild script.
 */
async function loadAllowSet(): Promise<Set<string>> {
  if (allowSet) return allowSet;
  try {
    const mod = (await import("./allow-list-data")) as {
      ALLOW_LIST: ReadonlySet<string>;
    };
    allowSet = new Set(mod.ALLOW_LIST);
  } catch {
    // File doesn't exist (local dev without gist) → empty set
    allowSet = new Set();
  }
  return allowSet;
}

/**
 * Check whether a mangled userId is on the allowlist.
 *
 * - AUTH_ENGINE=dev: allows only mangleUserId("0") (computed & cached once)
 * - AUTH_ENGINE=google: checks against the build-time allow-list from the GitHub Gist
 */
export async function isUserAllowed(mangledUserId: string): Promise<boolean> {
  if (env.authEngine === "dev") {
    if (devAllowedId === undefined) {
      devAllowedId = await mangleUserId("0");
    }
    return mangledUserId === devAllowedId;
  }

  const set = await loadAllowSet();
  return set.has(mangledUserId);
}
